import { STECKBRIEFE } from "./steckbrief-seed";
import type {
  ChipStatus,
  Clinic,
  ClinicPhoto,
  Indication,
  PhotoSlot,
  PhotoSource,
  Zulassung,
} from "./types";

const AS_OF = "09.2026";

type Draft = Omit<
  Clinic,
  "steckbrief" | "zulassung" | "datenstand" | "durationKurzWeeks" | "aufnahmeModus" | "photos"
> & {
  photos: ClinicPhoto[];
  durationKurzWeeks?: number | null;
  aufnahmeModus?: string;
};

function photo(
  slot: PhotoSlot,
  path: string | null,
  captionMotiv: string,
  alt: string,
  source: PhotoSource = "oeffentlich",
): ClinicPhoto {
  return {
    slot,
    imagePath: path,
    caption: path
      ? `${captionMotiv} · ${AS_OF} · ${source === "klinik" ? "Klinik" : "öffentlich"}`
      : `Foto nicht verfügbar · ${AS_OF} · fehlt`,
    alt: path ? alt : `${captionMotiv}: Foto nicht verfügbar`,
    source: path ? source : "fehlt",
    asOf: AS_OF,
  };
}

function photos(opts: {
  name: string;
  city: string;
  aussen: string;
  umgebung: string;
  speiseraum?: string | null;
  besonderheit: { file: string; motiv: string; alt: string }[];
}): ClinicPhoto[] {
  const list: ClinicPhoto[] = [
    photo("aussen", opts.aussen, "Außenansicht", `Außenansicht der ${opts.name} in ${opts.city}`),
    photo(
      "zimmer_bad",
      "/clinics/zimmer.jpg",
      "Zimmer / Bad",
      `Patientenzimmer mit Bad in der ${opts.name}, ohne Personen`,
    ),
    photo(
      "umgebung",
      opts.umgebung,
      "Umgebung / Lage",
      `Außenanlagen der ${opts.name} in ${opts.city}`,
    ),
  ];
  if (opts.speiseraum) {
    list.push(
      photo(
        "speiseraum",
        opts.speiseraum,
        "Speiseraum / Verpflegung",
        `Speiseraum der ${opts.name}`,
      ),
    );
  }
  for (const item of opts.besonderheit.slice(0, 3)) {
    list.push(photo("besonderheit", item.file, item.motiv, item.alt));
  }
  return list;
}

function zulassung(art: string, ahb: boolean, heilverfahren: boolean): Zulassung {
  const drv: ChipStatus =
    art === "drv" || art === "kirche" || art === "gemeinnuetzig" ? "vorhanden" : "unbekannt";
  return {
    drv,
    gkv: heilverfahren ? "vorhanden" : "unbekannt",
    ahb: ahb ? "vorhanden" : "nicht_angeboten",
    beihilfe: "unbekannt",
  };
}

const DRAFTS: Draft[] = [
  {
    id: "ck-seewiesen",
    name: "Klinik Seewiesen",
    shortName: "Seewiesen",
    city: "Starnberg",
    stateCode: "BY",
    stateName: "Bayern",
    traeger: "Deutsche Rentenversicherung Bayern Süd (Musterträger)",
    traegerArt: "drv",
    address: "Seeweg 12, 82319 Starnberg",
    phone: "08151 0000-0",
    email: "aufnahme@seewiesen.example",
    website: "https://example.org/seewiesen",
    indicationAreas: ["psychosomatik"],
    substances: ["depression", "angst", "erschopfung", "schmerz"],
    therapyForms: ["Einzeltherapie", "Gruppentherapie", "Körpertherapie", "Kreativtherapie"],
    durationWeeksMin: 4,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: false,
    trauma: true,
    jungeErwachsene: false,
    placesEstimate: 118,
    occupancyIndex: 1.12,
    waitBaseDays: 32,
    waitVarianceDays: 10,
    sortOrder: 1,
    photos: photos({
      name: "Klinik Seewiesen",
      city: "Starnberg",
      aussen: "/clinics/aussen-see.jpg",
      umgebung: "/clinics/umgebung-park.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/ruheraum.jpg", motiv: "Ruheraum", alt: "Unbelebter Ruheraum der Klinik Seewiesen" },
        { file: "/clinics/umgebung-garten.jpg", motiv: "Therapiegarten", alt: "Garten der Klinik Seewiesen, ohne Personen" },
      ],
    }),
  },
  {
    id: "ck-nordlicht",
    name: "Fachklinik Nordlicht",
    shortName: "Nordlicht",
    city: "Schleswig",
    stateCode: "SH",
    stateName: "Schleswig-Holstein",
    traeger: "Nordlicht gGmbH (gemeinnützig, Musterträger)",
    traegerArt: "gemeinnuetzig",
    address: "Holmer Weg 8, 24837 Schleswig",
    phone: "04621 0000-0",
    email: "info@nordlicht.example",
    website: "https://example.org/nordlicht",
    indicationAreas: ["sucht"],
    substances: ["alkohol", "drogen", "medikamente", "gluecksspiel"],
    therapyForms: ["Motivational Interviewing", "Rückfallprävention", "Bezugsgruppe", "Arbeitstherapie"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: true,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 86,
    occupancyIndex: 1.22,
    waitBaseDays: 56,
    waitVarianceDays: 14,
    sortOrder: 2,
    photos: photos({
      name: "Fachklinik Nordlicht",
      city: "Schleswig",
      aussen: "/clinics/aussen-nord.jpg",
      umgebung: "/clinics/umgebung-park.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/werkstatt.jpg", motiv: "Arbeitstherapie", alt: "Werkstatt der Fachklinik Nordlicht, ohne Personen" },
      ],
    }),
  },
  {
    id: "ck-auwald",
    name: "Haus am Auwald",
    shortName: "Auwald",
    city: "Freiburg",
    stateCode: "BW",
    stateName: "Baden-Württemberg",
    traeger: "Diakonisches Werk Musterträger",
    traegerArt: "kirche",
    address: "Auwaldstraße 21, 79110 Freiburg",
    phone: "0761 0000-0",
    email: "aufnahme@auwald.example",
    website: "https://example.org/auwald",
    indicationAreas: ["dual"],
    substances: ["alkohol", "drogen", "depression", "angst", "trauma"],
    therapyForms: ["Integrative Dualbehandlung", "Skills-Gruppe", "Traumamodul", "Psychiatriekonsil"],
    durationWeeksMin: 8,
    durationWeeksMax: 14,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: false,
    trauma: true,
    jungeErwachsene: false,
    placesEstimate: 64,
    occupancyIndex: 1.3,
    waitBaseDays: 70,
    waitVarianceDays: 16,
    sortOrder: 3,
    photos: photos({
      name: "Haus am Auwald",
      city: "Freiburg",
      aussen: "/clinics/aussen-wald.jpg",
      umgebung: "/clinics/umgebung-garten.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/ruheraum.jpg", motiv: "Reizarmer Ruheraum", alt: "Ruheraum im Haus am Auwald" },
      ],
    }),
  },
  {
    id: "ck-weserblick",
    name: "Reha-Zentrum Weserblick",
    shortName: "Weserblick",
    city: "Bad Oeynhausen",
    stateCode: "NW",
    stateName: "Nordrhein-Westfalen",
    traeger: "DRV Westfalen (Musterträger)",
    traegerArt: "drv",
    address: "Parkallee 4, 32545 Bad Oeynhausen",
    phone: "05731 0000-0",
    email: "ahb@weserblick.example",
    website: "https://example.org/weserblick",
    indicationAreas: ["psychosomatik"],
    substances: ["depression", "angst", "erschopfung", "schmerz"],
    therapyForms: ["AHB-Standard", "Gruppentherapie", "Physiotherapie", "Ergotherapie"],
    durationWeeksMin: 3,
    durationWeeksMax: 5,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: false,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 160,
    occupancyIndex: 1.05,
    waitBaseDays: 24,
    waitVarianceDays: 8,
    sortOrder: 4,
    photos: photos({
      name: "Reha-Zentrum Weserblick",
      city: "Bad Oeynhausen",
      aussen: "/clinics/aussen-kur.jpg",
      umgebung: "/clinics/umgebung-park.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/ruheraum.jpg", motiv: "Stiller Raum", alt: "Stiller Raum im Reha-Zentrum Weserblick" },
      ],
    }),
  },
  {
    id: "ck-bergstrasse",
    name: "Fachklinik Bergstraße",
    shortName: "Bergstraße",
    city: "Heppenheim",
    stateCode: "HE",
    stateName: "Hessen",
    traeger: "Männerhilfe Bergstraße e. V. (Musterträger)",
    traegerArt: "gemeinnuetzig",
    address: "Weinberg 3, 64646 Heppenheim",
    phone: "06252 0000-0",
    email: "info@bergstrasse.example",
    website: "https://example.org/bergstrasse",
    indicationAreas: ["sucht"],
    substances: ["alkohol", "drogen", "medikamente"],
    therapyForms: ["Männerspezifische Gruppe", "Rückfallprävention", "Sport", "Arbeitstherapie"],
    durationWeeksMin: 12,
    durationWeeksMax: 15,
    genderSetting: "maenner",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 72,
    occupancyIndex: 1.18,
    waitBaseDays: 48,
    waitVarianceDays: 12,
    sortOrder: 5,
    photos: photos({
      name: "Fachklinik Bergstraße",
      city: "Heppenheim",
      aussen: "/clinics/aussen-wald.jpg",
      umgebung: "/clinics/umgebung-garten.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/werkstatt.jpg", motiv: "Werkstatt", alt: "Arbeitstherapie der Fachklinik Bergstraße" },
      ],
    }),
  },
  {
    id: "ck-elbmarsch",
    name: "Therapiezentrum Elbmarsch",
    shortName: "Elbmarsch",
    city: "Lüneburg",
    stateCode: "NI",
    stateName: "Niedersachsen",
    traeger: "Frauenwerk Elbe gGmbH (Musterträger)",
    traegerArt: "gemeinnuetzig",
    address: "Marschdeich 9, 21335 Lüneburg",
    phone: "04131 0000-0",
    email: "info@elbmarsch.example",
    website: "https://example.org/elbmarsch",
    indicationAreas: ["sucht"],
    substances: ["alkohol", "drogen", "medikamente"],
    therapyForms: ["Frauenspezifische Therapie", "Trauma-sensible Gruppe", "Körperarbeit", "Elternmodul"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "frauen",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: true,
    substitution: false,
    gluecksspiel: false,
    trauma: true,
    jungeErwachsene: false,
    placesEstimate: 54,
    occupancyIndex: 1.26,
    waitBaseDays: 62,
    waitVarianceDays: 14,
    sortOrder: 6,
    photos: photos({
      name: "Therapiezentrum Elbmarsch",
      city: "Lüneburg",
      aussen: "/clinics/aussen-see.jpg",
      umgebung: "/clinics/umgebung-park.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/umgebung-garten.jpg", motiv: "Hof mit Spielbereich", alt: "Garten des Therapiezentrums Elbmarsch" },
        { file: "/clinics/ruheraum.jpg", motiv: "Stabilisierungsraum", alt: "Stabilisierungsraum Elbmarsch" },
      ],
    }),
  },
  {
    id: "ck-rosenhoehe",
    name: "Klinik Rosenhöhe",
    shortName: "Rosenhöhe",
    city: "Stuttgart",
    stateCode: "BW",
    stateName: "Baden-Württemberg",
    traeger: "Katholische Reha-Stiftung Musterträger",
    traegerArt: "kirche",
    address: "Rosenweg 15, 70378 Stuttgart",
    phone: "0711 0000-0",
    email: "info@rosenhoehe.example",
    website: "https://example.org/rosenhoehe",
    indicationAreas: ["psychosomatik"],
    substances: ["depression", "angst", "erschopfung", "ess"],
    therapyForms: ["tiefenpsychologisch fundiert", "Gruppenanalyse", "Kreativtherapie", "Seelsorge optional"],
    durationWeeksMin: 5,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 96,
    occupancyIndex: 1.14,
    waitBaseDays: 38,
    waitVarianceDays: 11,
    sortOrder: 7,
    photos: photos({
      name: "Klinik Rosenhöhe",
      city: "Stuttgart",
      aussen: "/clinics/aussen-stadt.jpg",
      umgebung: "/clinics/umgebung-garten.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/ruheraum.jpg", motiv: "Stiller Raum", alt: "Stiller Raum der Klinik Rosenhöhe" },
      ],
    }),
  },
  {
    id: "ck-eifelhoehe",
    name: "Fachklinik Eifelhöhe",
    shortName: "Eifelhöhe",
    city: "Daun",
    stateCode: "RP",
    stateName: "Rheinland-Pfalz",
    traeger: "Eifelhilfe gGmbH (Musterträger)",
    traegerArt: "gemeinnuetzig",
    address: "Höhenweg 2, 54550 Daun",
    phone: "06592 0000-0",
    email: "info@eifelhoehe.example",
    website: "https://example.org/eifelhoehe",
    indicationAreas: ["sucht"],
    substances: ["alkohol", "gluecksspiel", "drogen"],
    therapyForms: ["Rückfallprävention", "Glücksspielmodul", "Naturgruppe", "Arbeitstherapie"],
    durationWeeksMin: 10,
    durationWeeksMax: 14,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: true,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 68,
    occupancyIndex: 1.08,
    waitBaseDays: 42,
    waitVarianceDays: 12,
    sortOrder: 8,
    photos: photos({
      name: "Fachklinik Eifelhöhe",
      city: "Daun",
      aussen: "/clinics/aussen-wald.jpg",
      umgebung: "/clinics/umgebung-garten.jpg",
      besonderheit: [
        { file: "/clinics/werkstatt.jpg", motiv: "Werkstatt", alt: "Werkstatt der Fachklinik Eifelhöhe" },
      ],
    }),
  },
  {
    id: "ck-lichtblick",
    name: "Haus Lichtblick",
    shortName: "Lichtblick",
    city: "Dresden",
    stateCode: "SN",
    stateName: "Sachsen",
    traeger: "Lichtblick Sachsen gGmbH (Musterträger)",
    traegerArt: "gemeinnuetzig",
    address: "Elbhang 18, 01326 Dresden",
    phone: "0351 0000-0",
    email: "info@lichtblick.example",
    website: "https://example.org/lichtblick",
    indicationAreas: ["dual"],
    substances: ["alkohol", "drogen", "depression", "angst"],
    therapyForms: ["Dualgruppe", "Psychoedukation", "Skills", "Sozialberatung"],
    durationWeeksMin: 8,
    durationWeeksMax: 12,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: false,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 58,
    occupancyIndex: 1.2,
    waitBaseDays: 52,
    waitVarianceDays: 13,
    sortOrder: 9,
    photos: photos({
      name: "Haus Lichtblick",
      city: "Dresden",
      aussen: "/clinics/aussen-stadt.jpg",
      umgebung: "/clinics/umgebung-park.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/werkstatt.jpg", motiv: "Alltagsnahe Werkstatt", alt: "Werkstatt im Haus Lichtblick" },
      ],
    }),
  },
  {
    id: "ck-haffkueste",
    name: "Rehaklinik Haffküste",
    shortName: "Haffküste",
    city: "Heringsdorf",
    stateCode: "MV",
    stateName: "Mecklenburg-Vorpommern",
    traeger: "Ostsee-Reha AG (Musterträger)",
    traegerArt: "privat",
    address: "Dünenweg 1, 17424 Heringsdorf",
    phone: "038378 000-0",
    email: "info@haffkueste.example",
    website: "https://example.org/haffkueste",
    indicationAreas: ["psychosomatik"],
    substances: ["depression", "angst", "erschopfung"],
    therapyForms: ["Klimatherapie", "Gruppentherapie", "Physio", "Kreativtherapie"],
    durationWeeksMin: 4,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: false,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 140,
    occupancyIndex: 0.96,
    waitBaseDays: 28,
    waitVarianceDays: 9,
    sortOrder: 10,
    photos: photos({
      name: "Rehaklinik Haffküste",
      city: "Heringsdorf",
      aussen: "/clinics/aussen-kueste.jpg",
      umgebung: "/clinics/umgebung-park.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/ruheraum.jpg", motiv: "Stiller Raum landseitig", alt: "Ruheraum der Rehaklinik Haffküste" },
      ],
    }),
  },
  {
    id: "ck-isargrund",
    name: "Fachklinik Isargrund",
    shortName: "Isargrund",
    city: "Bad Tölz",
    stateCode: "BY",
    stateName: "Bayern",
    traeger: "Isargrund gGmbH (Musterträger)",
    traegerArt: "gemeinnuetzig",
    address: "Isarauen 7, 83646 Bad Tölz",
    phone: "08041 0000-0",
    email: "info@isargrund.example",
    website: "https://example.org/isargrund",
    indicationAreas: ["sucht"],
    substances: ["medikamente", "alkohol"],
    therapyForms: ["Medikamentenentwöhnung", "Schmerzgruppe", "Einzeltherapie", "Körpertherapie"],
    durationWeeksMin: 10,
    durationWeeksMax: 13,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 60,
    occupancyIndex: 1.15,
    waitBaseDays: 50,
    waitVarianceDays: 12,
    sortOrder: 11,
    photos: photos({
      name: "Fachklinik Isargrund",
      city: "Bad Tölz",
      aussen: "/clinics/aussen-see.jpg",
      umgebung: "/clinics/umgebung-garten.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/ruheraum.jpg", motiv: "Reizarmer Gruppenraum", alt: "Gruppenraum der Fachklinik Isargrund" },
      ],
    }),
  },
  {
    id: "ck-spreeaue",
    name: "Therapiehaus Spreeaue",
    shortName: "Spreeaue",
    city: "Berlin",
    stateCode: "BE",
    stateName: "Berlin",
    traeger: "Spreeaue gGmbH (Musterträger)",
    traegerArt: "gemeinnuetzig",
    address: "Spreeweg 40, 12435 Berlin",
    phone: "030 0000-0",
    email: "info@spreeaue.example",
    website: "https://example.org/spreeaue",
    indicationAreas: ["psychosomatik"],
    substances: ["depression", "angst", "trauma", "erschopfung"],
    therapyForms: ["Tagesklinik", "Stationär", "Skills", "Traumamodul"],
    durationWeeksMin: 4,
    durationWeeksMax: 8,
    genderSetting: "gemischt",
    setting: "beides",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: false,
    trauma: true,
    jungeErwachsene: false,
    placesEstimate: 48,
    occupancyIndex: 1.24,
    waitBaseDays: 40,
    waitVarianceDays: 12,
    sortOrder: 12,
    photos: photos({
      name: "Therapiehaus Spreeaue",
      city: "Berlin",
      aussen: "/clinics/aussen-stadt.jpg",
      umgebung: "/clinics/umgebung-park.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/werkstatt.jpg", motiv: "Kreativtherapie", alt: "Kreativraum im Therapiehaus Spreeaue" },
      ],
    }),
  },
  {
    id: "ck-teutoburg",
    name: "Klinik Teutoburg",
    shortName: "Teutoburg",
    city: "Bad Rothenfelde",
    stateCode: "NW",
    stateName: "Nordrhein-Westfalen",
    traeger: "Teutoburg-Reha gGmbH (Musterträger)",
    traegerArt: "gemeinnuetzig",
    address: "Salzallee 11, 49214 Bad Rothenfelde",
    phone: "05424 0000-0",
    email: "info@teutoburg.example",
    website: "https://example.org/teutoburg",
    indicationAreas: ["sucht"],
    substances: ["alkohol", "drogen", "substitution"],
    therapyForms: ["Substitutionsumstellung", "Entwöhnung", "Bezugsgruppe", "Arbeitstherapie"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    substitution: true,
    gluecksspiel: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 80,
    occupancyIndex: 1.19,
    waitBaseDays: 58,
    waitVarianceDays: 14,
    sortOrder: 13,
    photos: photos({
      name: "Klinik Teutoburg",
      city: "Bad Rothenfelde",
      aussen: "/clinics/aussen-kur.jpg",
      umgebung: "/clinics/umgebung-garten.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/ruheraum.jpg", motiv: "Stiller Raum", alt: "Ruheraum der Klinik Teutoburg" },
      ],
    }),
  },
  {
    id: "ck-mainbogen",
    name: "Fachklinik Mainbogen",
    shortName: "Mainbogen",
    city: "Würzburg",
    stateCode: "BY",
    stateName: "Bayern",
    traeger: "Mainbogen Stiftung (Musterträger)",
    traegerArt: "gemeinnuetzig",
    address: "Mainkai 22, 97070 Würzburg",
    phone: "0931 0000-0",
    email: "info@mainbogen.example",
    website: "https://example.org/mainbogen",
    indicationAreas: ["dual"],
    substances: ["alkohol", "drogen", "depression", "trauma"],
    therapyForms: ["Dualbehandlung", "Traumastabilisierung", "Skills", "Sozialberatung"],
    durationWeeksMin: 8,
    durationWeeksMax: 13,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: false,
    trauma: true,
    jungeErwachsene: false,
    placesEstimate: 52,
    occupancyIndex: 1.27,
    waitBaseDays: 66,
    waitVarianceDays: 15,
    sortOrder: 14,
    photos: photos({
      name: "Fachklinik Mainbogen",
      city: "Würzburg",
      aussen: "/clinics/aussen-stadt.jpg",
      umgebung: "/clinics/umgebung-park.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/ruheraum.jpg", motiv: "Stabilisierungsraum", alt: "Stabilisierungsraum der Fachklinik Mainbogen" },
      ],
    }),
  },
  {
    id: "ck-rothaar",
    name: "Haus am Rothaarsteig",
    shortName: "Rothaarsteig",
    city: "Winterberg",
    stateCode: "NW",
    stateName: "Nordrhein-Westfalen",
    traeger: "Jugendhilfe Sauerland gGmbH (Musterträger)",
    traegerArt: "gemeinnuetzig",
    address: "Steig 5, 59955 Winterberg",
    phone: "02981 0000-0",
    email: "info@rothaar.example",
    website: "https://example.org/rothaar",
    indicationAreas: ["sucht"],
    substances: ["alkohol", "drogen"],
    therapyForms: ["Jungerwachsenengruppe", "Sport", "Schule/Beruf", "Bezugsgruppe"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: true,
    trauma: false,
    jungeErwachsene: true,
    placesEstimate: 44,
    occupancyIndex: 1.11,
    waitBaseDays: 44,
    waitVarianceDays: 11,
    sortOrder: 15,
    photos: photos({
      name: "Haus am Rothaarsteig",
      city: "Winterberg",
      aussen: "/clinics/aussen-wald.jpg",
      umgebung: "/clinics/umgebung-garten.jpg",
      besonderheit: [
        { file: "/clinics/werkstatt.jpg", motiv: "Werkstatt", alt: "Werkstatt im Haus am Rothaarsteig" },
        { file: "/clinics/umgebung-park.jpg", motiv: "Sportgelände", alt: "Außengelände am Rothaarsteig, ohne Personen" },
      ],
    }),
  },
  {
    id: "ck-alsterufer",
    name: "Klinik Alsterufer",
    shortName: "Alsterufer",
    city: "Hamburg",
    stateCode: "HH",
    stateName: "Hamburg",
    traeger: "Hanse-Reha gGmbH (Musterträger)",
    traegerArt: "gemeinnuetzig",
    address: "Alsterufer 28, 20354 Hamburg",
    phone: "040 0000-0",
    email: "info@alsterufer.example",
    website: "https://example.org/alsterufer",
    indicationAreas: ["psychosomatik"],
    substances: ["depression", "angst", "erschopfung"],
    therapyForms: ["AHB", "Gruppentherapie", "Stadtnahe Belastungserprobung", "Physio"],
    durationWeeksMin: 3,
    durationWeeksMax: 5,
    genderSetting: "gemischt",
    setting: "beides",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    substitution: false,
    gluecksspiel: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 72,
    occupancyIndex: 1.17,
    waitBaseDays: 30,
    waitVarianceDays: 9,
    sortOrder: 16,
    photos: photos({
      name: "Klinik Alsterufer",
      city: "Hamburg",
      aussen: "/clinics/aussen-stadt.jpg",
      umgebung: "/clinics/umgebung-park.jpg",
      speiseraum: "/clinics/speiseraum.jpg",
      besonderheit: [
        { file: "/clinics/ruheraum.jpg", motiv: "Leseraum zum Garten", alt: "Leseraum der Klinik Alsterufer" },
      ],
    }),
  },
];

export const CLINIC_SEED: Clinic[] = DRAFTS.map((row) => {
  const steckbrief = STECKBRIEFE[row.id];
  if (!steckbrief) {
    throw new Error(`Steckbrief fehlt für ${row.id}`);
  }
  return {
    ...row,
    durationKurzWeeks: row.durationKurzWeeks ?? Math.min(row.durationWeeksMin, 4),
    aufnahmeModus: row.aufnahmeModus ?? "rollierend nach Kostenzusage",
    zulassung: zulassung(row.traegerArt, row.ahb, row.heilverfahren),
    datenstand: {
      geprueft: "2026-09-01",
      quellen: "Musterprofil Lohklar · öffentlich übliche Träger- und Settingangaben",
    },
    steckbrief,
  };
});

export const INDICATION_SET = new Set<Indication>(["sucht", "psychosomatik", "dual"]);
