import type { GenderSetting, Indication, SettingKind } from "./types.ts";
import type { HouseSpec, RoomKind } from "./katalog-houses.ts";

const NA = "Angabe liegt nicht vor";
const STATES: Record<string, string> = {
  BW: "Baden-Württemberg",
  BY: "Bayern",
  BE: "Berlin",
  BB: "Brandenburg",
  HB: "Bremen",
  HH: "Hamburg",
  HE: "Hessen",
  MV: "Mecklenburg-Vorpommern",
  NI: "Niedersachsen",
  NW: "Nordrhein-Westfalen",
  RP: "Rheinland-Pfalz",
  SL: "Saarland",
  SN: "Sachsen",
  ST: "Sachsen-Anhalt",
  SH: "Schleswig-Holstein",
  TH: "Thüringen",
};

const psycho = ["depression", "angst", "erschopfung"];
const suchtAll = ["alkohol", "drogen", "medikamente"];
const dualSub = ["alkohol", "drogen", "medikamente", "depression", "angst"];
const suchtAlkMed = ["alkohol", "medikamente"];
const einzelGruppe = ["Einzeltherapie", "Gruppentherapie", "Körpertherapie", "Sozialberatung"];

type Kind = Indication;

type Row = {
  id: string;
  name: string;
  short: string;
  city: string;
  plz: string;
  street: string;
  st: string;
  traeger: string;
  art: HouseSpec["traegerArt"];
  phone?: string;
  email?: string;
  web: string;
  kind: Kind;
  alk?: boolean | null;
  drog?: boolean | null;
  med?: boolean | null;
  glueck?: boolean;
  subst?: boolean;
  substM?: string;
  dmin: number;
  dmax: number;
  gender?: GenderSetting;
  setting?: SettingKind;
  ahb?: boolean;
  hv?: boolean;
  bar?: boolean;
  kinder?: boolean;
  trauma?: boolean;
  jung?: boolean;
  room?: RoomKind;
  wait?: number;
  places?: number;
  occ?: number;
  lage: string;
  fokus: string;
  facts: string[];
};

function row(r: Row, sortOrder: number): HouseSpec {
  const sucht = r.kind === "sucht" || r.kind === "dual";
  const alkohol = r.alk === undefined ? (sucht ? true : null) : r.alk;
  const drogen = r.drog === undefined ? (sucht ? true : null) : r.drog;
  const medikamente = r.med === undefined ? (sucht ? true : null) : r.med;
  const substances =
    r.kind === "psychosomatik"
      ? [...psycho]
      : r.kind === "dual"
        ? [...dualSub]
        : drogen === false
          ? [...suchtAlkMed]
          : [...suchtAll];
  return {
    id: r.id,
    name: r.name,
    shortName: r.short,
    city: r.city,
    plz: r.plz,
    street: r.street,
    stateCode: r.st,
    stateName: STATES[r.st] ?? r.st,
    traeger: r.traeger,
    traegerArt: r.art,
    phone: r.phone ?? NA,
    email: r.email ?? NA,
    website: r.web,
    indicationAreas: [r.kind],
    alkohol,
    drogen,
    medikamente,
    gluecksspiel: r.glueck ?? false,
    substitution: r.subst ?? false,
    substMittel: r.substM ?? (r.subst ? NA : sucht ? NA : "nicht angeboten"),
    substances,
    therapyForms: [...einzelGruppe],
    durationWeeksMin: r.dmin,
    durationWeeksMax: r.dmax,
    genderSetting: r.gender ?? "gemischt",
    setting: r.setting ?? "stationaer",
    ahb: r.ahb ?? r.kind === "psychosomatik",
    heilverfahren: r.hv ?? true,
    barrierefrei: r.bar ?? false,
    angehoerigenarbeit: true,
    kinderbetreuung: r.kinder ?? false,
    trauma: r.trauma ?? false,
    jungeErwachsene: r.jung ?? false,
    placesEstimate: r.places ?? (sucht ? 80 : 120),
    occupancyIndex: r.occ ?? 1.15,
    waitBaseDays: r.wait ?? (sucht ? 48 : 32),
    waitVarianceDays: sucht ? 14 : 10,
    sortOrder,
    speiseraum: true,
    besonderheit: sucht ? "werkstatt" : "garten",
    room: r.room ?? "unbekannt",
    wahl: "unbekannt",
    lage: r.lage,
    fokus: r.fokus,
    facts: r.facts.slice(0, 3),
  };
}

const ROWS: Row[] = [
  {
    id: "ck-huettenbuehl",
    name: "Reha-Zentrum Bad Dürrheim, Klinik Hüttenbühl",
    short: "Klinik Hüttenbühl",
    city: "Bad Dürrheim",
    plz: "78073",
    street: "Wittmannstalstraße 5",
    st: "BW",
    traeger: "Deutsche Rentenversicherung Bund",
    art: "drv",
    phone: "07726 925-0",
    email: "reha-klinik.huettenbuehl@drv-bund.de",
    web: "https://www.reha-klinik-huettenbuehl.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "beides",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: true,
    jung: false,
    room: "unbekannt",
    lage: "Zwischen Schwarzwald und Schwäbischer Alb im heilklimatischen Kurort Bad Dürrheim.",
    fokus: "DRV-Bund-Fachklinik für psychische und psychosomatische Krankheiten inkl. Traumafolgestörungen.",
    facts: ["Stationäre und ambulante psychosomatische Reha.", "Traumafolgestörungen werden öffentlich genannt.", "DRV-eigene Klinik, nicht identisch mit der Luisenklinik am Ort."],
  },
  {
    id: "ck-klinik-rhoen",
    name: "Reha-Zentrum Bad Kissingen, Klinik Rhön",
    short: "Klinik Rhön",
    city: "Bad Kissingen",
    plz: "97688",
    street: "Kurhausstraße 20",
    st: "BY",
    traeger: "Deutsche Rentenversicherung Bund",
    art: "drv",
    phone: "0971 85-02",
    email: "reha-klinik.rhoen@drv-bund.de",
    web: "https://www.reha-klinik-rhoen.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "beides",
    ahb: true,
    hv: true,
    kinder: true,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Im UNESCO-Welterbe-Kurort Bad Kissingen am Park, nahe dem Stadtzentrum.",
    fokus: "Psychosomatische Rehabilitation mit Mitbehandlung internistischer Begleiterkrankungen.",
    facts: ["DRV-Bund-Klinik im bayerischen Staatsbad.", "Stationär und ambulant möglich.", "Begleitkinder 3–12 Jahre nach Absprache laut Klinikseite."],
  },
  {
    id: "ck-hartwald",
    name: "Reha-Zentrum Bad Brückenau, Klinik Hartwald",
    short: "Klinik Hartwald",
    city: "Bad Brückenau",
    plz: "97769",
    street: "Schlüchterner Straße 4",
    st: "BY",
    traeger: "Deutsche Rentenversicherung Bund",
    art: "drv",
    phone: "09741 82-0",
    email: "reha-klinik.hartwald@drv-bund.de",
    web: "https://www.reha-klinik-hartwald.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Im bayerischen Staatsbad Bad Brückenau in der Rhön.",
    fokus: "Duale Reha Psycho-Gastroenterologie: Psychosomatik kombiniert mit Gastroenterologie.",
    facts: ["DRV-eigene Klinik Hartwald.", "Duale Reha Psycho-Gastroenterologie öffentlich genannt.", "AHB und Heilverfahren."],
  },
  {
    id: "ck-sprudelhof",
    name: "Rehabilitationszentrum am Sprudelhof",
    short: "Sprudelhof",
    city: "Bad Nauheim",
    plz: "61231",
    street: "Ludwigstraße 25-31",
    st: "HE",
    traeger: "Deutsche Rentenversicherung Hessen",
    art: "drv",
    phone: "06032 806-0",
    email: "rehabilitationszentrum-am-sprudelhof@drv-hessen.de",
    web: "https://www.rehabilitationszentrum-am-sprudelhof.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Unmittelbar am historischen Jugendstil-Sprudelhof und Kurpark Bad Nauheim.",
    fokus: "Kardiologie und psychosomatische Medizin, psychodynamisch-verhaltenstherapeutisch.",
    facts: ["DRV Hessen, Klinik am Sprudelhof.", "Indikationen u. a. Depression, Angst, Burnout, somatoforme Störungen laut Klinikseite.", "Nicht identisch mit der Klinik Taunus am selben Ort."],
  },
  {
    id: "ck-hoehenklinik-bischofsgruen",
    name: "Höhenklinik Bischofsgrün",
    short: "Höhenklinik Bischofsgrün",
    city: "Bischofsgrün",
    plz: "95493",
    street: "Fröbershammer 12",
    st: "BY",
    traeger: "Deutsche Rentenversicherung Nordbayern",
    art: "drv",
    phone: "09276 88-0",
    email: "service@hoehenklinik-bischofsgruen.de",
    web: "https://www.hoehenklinik-bischofsgruen.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Heilklimatischer Kurort im Fichtelgebirge, umgeben von Wäldern.",
    fokus: "Reha-Fachklinik für psychosomatische Medizin und Psychotherapie, verhaltenstherapeutisch geprägt.",
    facts: ["DRV Nordbayern.", "Psychosomatik plus RV-Fit-Prävention auf der Klinikseite.", "In der DRV-Liste Reha bei psychischen Erkrankungen."],
  },
  {
    id: "ck-lindenberg-ried",
    name: "Klinik Lindenberg-Ried",
    short: "Lindenberg-Ried",
    city: "Lindenberg im Allgäu",
    plz: "88161",
    street: "Ried 1a",
    st: "BY",
    traeger: "Deutsche Rentenversicherung Schwaben",
    art: "drv",
    phone: "08381 804-0",
    email: "klinik-lindenberg@drv-schwaben.de",
    web: "https://www.klinik-lindenberg-ried.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "In reizvoller Hügellandschaft mit Blick auf die Allgäuer Alpen.",
    fokus: "Reha- und AHB-Fachklinik für Psychosomatik und Orthopädie, inkl. chronischer Schmerzstörungen.",
    facts: ["DRV Schwaben.", "Eigene Fachabteilung Psychosomatik.", "In der DRV-Liste Reha bei psychischen Erkrankungen."],
  },
  {
    id: "ck-paul-ehrlich",
    name: "Paul-Ehrlich-Klinik",
    short: "Paul-Ehrlich-Klinik",
    city: "Bad Homburg v. d. Höhe",
    plz: "61348",
    street: "Landgrafenstraße 2-8",
    st: "HE",
    traeger: "Deutsche Rentenversicherung Knappschaft-Bahn-See",
    art: "drv",
    phone: "06172 128-0",
    email: "bad-homburg-info@kbs.de",
    web: "https://www.paul-ehrlich-klinik.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Im Kurort Bad Homburg vor der Höhe, nördlich von Frankfurt.",
    fokus: "KBS-Rehaklinik für Orthopädie und Psychosomatik.",
    facts: ["Knappschaft-Bahn-See.", "Eigene Abteilung Psychosomatik.", "AHB und Heilverfahren."],
  },
  {
    id: "ck-chiemgau",
    name: "Chiemgau-Klinik Marquartstein",
    short: "Chiemgau-Klinik",
    city: "Marquartstein",
    plz: "83250",
    street: "Geisenhausen 1",
    st: "BY",
    traeger: "Deutsche Rentenversicherung Knappschaft-Bahn-See",
    art: "drv",
    phone: "08641 629-0",
    email: "chiemgau-klinik-info@kbs.de",
    web: "https://www.chiemgau-klinik.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Im Chiemgau in Marquartstein, Voralpenland südlich des Chiemsees.",
    fokus: "KBS-Rehaklinik für Orthopädie und Psychosomatik mit MBOR und VOR.",
    facts: ["Knappschaft-Bahn-See.", "Psychosomatik und Orthopädie am Standort.", "AHB, MBOR und VOR öffentlich genannt."],
  },
  {
    id: "ck-oberharz",
    name: "Rehazentrum Oberharz",
    short: "Rehazentrum Oberharz",
    city: "Clausthal-Zellerfeld",
    plz: "38678",
    street: "Schwarzenbacher Straße 19",
    st: "NI",
    traeger: "Deutsche Rentenversicherung Braunschweig-Hannover",
    art: "drv",
    phone: "05323 712-0",
    email: "info@rehazentrum-oberharz.de",
    web: "https://www.rehazentrum-oberharz.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "beides",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Auf einer Hochebene des Oberharzes am Ortsrand von Clausthal-Zellerfeld am Schwarzenbacher Teich.",
    fokus: "Schwerpunktklinik für Onkologie und Psychosomatik inkl. MBOR-Psychosomatik.",
    facts: ["DRV Braunschweig-Hannover.", "In der DRV-Liste Reha bei psychischen Erkrankungen.", "Klinikkompass führt das Haus unter psychosomatischer Reha."],
  },
  {
    id: "ck-goehren",
    name: "Rehabilitationsklinik Göhren",
    short: "Rehaklinik Göhren",
    city: "Göhren",
    plz: "18586",
    street: "Südstrand 6",
    st: "MV",
    traeger: "Deutsche Rentenversicherung Mitteldeutschland",
    art: "drv",
    phone: "038308 53-8",
    email: "rehaklinikgoehren@drv-md.de",
    web: "https://www.rehaklinik-goehren.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "beides",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Direkt hinter den Dünen am Südstrand des Ostseebads Göhren auf Rügen.",
    fokus: "Orthopädische und psychosomatische Rehabilitation der DRV Mitteldeutschland.",
    facts: ["Ostseelage auf Rügen.", "Stationär und ambulant.", "DRV-Liste Reha bei psychischen Erkrankungen."],
  },
  {
    id: "ck-wehrawald",
    name: "Reha-Zentrum Todtmoos – Klinik Wehrawald",
    short: "Klinik Wehrawald",
    city: "Todtmoos",
    plz: "79682",
    street: "Schwarzenbacher Straße 4",
    st: "BW",
    traeger: "Deutsche Rentenversicherung Bund",
    art: "drv",
    phone: "07674 903-0",
    email: "reha-klinik.wehrawald@drv-bund.de",
    web: "https://www.reha-klinik-wehrawald.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: true,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Auf 880 Höhenmetern im Südschwarzwald im heilklimatischen Kurort Todtmoos.",
    fokus: "Pneumologie, Psychosomatik und Duale Reha (Psycho-Pneumologie).",
    facts: ["DRV Bund, Klinik Wehrawald.", "Kinderbetreuung 3–12 Jahre auf der Klinikseite genannt.", "In der DRV-Liste Reha bei psychischen Erkrankungen."],
  },
  {
    id: "ck-klinik-saale",
    name: "Reha-Zentrum Bad Kissingen – Klinik Saale",
    short: "Klinik Saale",
    city: "Bad Kissingen",
    plz: "97688",
    street: "Pfaffstraße 10",
    st: "BY",
    traeger: "Deutsche Rentenversicherung Bund",
    art: "drv",
    phone: "0971 850-1",
    email: "reha-klinik.saale@drv-bund.de",
    web: "https://www.reha-klinik-saale.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "In der UNESCO-Welterbestadt Bad Kissingen, Pfaffstraße 10.",
    fokus: "Diabetes, Adipositas und psychosomatische Krankheitsbilder inkl. Psychodiabetologie.",
    facts: ["DRV Bund, Klinik Saale.", "Eigene Abteilung Psychosomatik.", "Nicht identisch mit der Klinik Rhön am selben Reha-Zentrum."],
  },
  {
    id: "ck-zapr-glotterbad",
    name: "Zentrum für Ambulante Psychosomatische Rehabilitation Glotterbad",
    short: "ZAPR Glotterbad",
    city: "Glottertal",
    plz: "79286",
    street: "Gehrenstraße 3",
    st: "BW",
    traeger: "Deutsche Rentenversicherung Baden-Württemberg",
    art: "drv",
    web: "https://www.rehaklinik-glotterbad.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "tagesklinik",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Glottertal bei Freiburg, ganztägig ambulantes Zentrum neben der Rehaklinik Glotterbad.",
    fokus: "Ganztägig ambulante psychosomatische Rehabilitation.",
    facts: ["DRV-Liste Reha bei psychischen Erkrankungen.", "Tagesklinik, nicht das stationäre Haus Glotterbad.", "Adresse Gehrenstraße 3 laut DRV."],
  },
  {
    id: "ck-buching",
    name: "Rehaklinik Buching",
    short: "Rehaklinik Buching",
    city: "Halblech",
    plz: "87642",
    street: "Rauhenbichl 9",
    st: "BY",
    traeger: "Kur + Reha GmbH",
    art: "gemeinnuetzig",
    phone: "08368 79-0",
    email: "rehaklinik.buching@kur.org",
    web: "https://www.rehaklinik-buching.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 4,
    dmax: 5,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Auf 800 m Höhe im Ostallgäu in parkähnlicher Anlage.",
    fokus: "Psychosomatische Fachklinik mit bio-psycho-sozialem Konzept.",
    facts: ["Kur + Reha GmbH, Paritätischer Wohlfahrtsverband.", "Versorgungsvertrag § 111 SGB V laut Klinikseite.", "Allgäuer Höhenlage."],
  },
  {
    id: "ck-sachsenklinik",
    name: "Sachsenklinik Bad Lausick",
    short: "Sachsenklinik",
    city: "Bad Lausick",
    plz: "04651",
    street: "Parkstraße 2",
    st: "SN",
    traeger: "Michels Kliniken / Sachsenklinik GmbH & Co. KG",
    art: "privat",
    phone: "034345 3-0",
    email: "info@sachsenklinik.de",
    web: "https://www.sachsenklinik.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "beides",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Im sächsischen Heilbad Bad Lausick in hügeliger Waldlandschaft.",
    fokus: "Große psychosomatische Abteilung neben Neurologie und Orthopädie.",
    facts: ["Klinikkompass führt das Haus unter psychosomatischer Reha.", "MBOR wird öffentlich genannt.", "Nicht identisch mit MEDIAN Bad Lausick."],
  },
  {
    id: "ck-alpcura",
    name: "Alpcura Fachklinik Allgäu",
    short: "Alpcura Allgäu",
    city: "Pfronten",
    plz: "87459",
    street: "Peter-Heel-Straße 29",
    st: "BY",
    traeger: "Alpcura",
    art: "privat",
    phone: "08363 691-0",
    web: "https://www.fachklinik-allgaeu.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Im Luftkurort Pfronten-Ried auf rund 850 m vor Allgäuer und Tiroler Alpen.",
    fokus: "Stationäre psychosomatische Rehabilitation neben Pneumologie.",
    facts: ["Reha für Psychosomatik und Pneumologie laut Klinikseite.", "DRV/GKV-Heilverfahren und AHB.", "Allgäuer Höhenlage."],
  },
  {
    id: "ck-wittekind",
    name: "VITREA Wittekindklinik Bad Essen",
    short: "Wittekindklinik",
    city: "Bad Essen",
    plz: "49152",
    street: "Empterweg 5",
    st: "NI",
    traeger: "VITREA",
    art: "privat",
    phone: "05472 935-01",
    email: "info.wittekind-bad-essen@vitrea.de",
    web: "https://www.vitrea-gesundheit.de/reha/vitrea-wittekindklinik-bad-essen/",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: true,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Im Kurort Bad Essen im Osnabrücker Land, Klinikgelände Empterweg.",
    fokus: "Rehabilitationsklinik ausschließlich für psychische und psychosomatische Erkrankungen.",
    facts: ["VITREA-Gruppe, anderes Haus als Berghofklinik und Wiehengebirge am Ort.", "Begleitkinder bis 6 Jahre laut Trägerseite.", "Erwachsene Frauen und Männer."],
  },
  {
    id: "ck-mediclin-baar",
    name: "MEDICLIN Baar Klinik",
    short: "Baar Klinik",
    city: "Königsfeld",
    plz: "78126",
    street: "Parkstraße 10",
    st: "BW",
    traeger: "MEDICLIN",
    art: "privat",
    phone: "07725 96-0",
    email: "info.baar-klinik@mediclin.de",
    web: "https://www.albert-schweitzer-klinik.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Im heilklimatischen Kneippkurort Königsfeld im Schwarzwald, unter einem Dach mit der Albert-Schweitzer-Klinik.",
    fokus: "Fachklinik für Psychosomatik und Verhaltensmedizin.",
    facts: ["MEDICLIN-Campus Königsfeld.", "Nicht die kardiologische Albert-Schweitzer-Klinik, sondern die Baar Klinik.", "AHB und Heilverfahren."],
  },
  {
    id: "ck-deignis",
    name: "de'ignis-Fachklinik",
    short: "de'ignis",
    city: "Egenhausen",
    plz: "72227",
    street: "Walddorfer Straße 23",
    st: "BW",
    traeger: "de'ignis-Fachklinik gGmbH",
    art: "kirche",
    phone: "07453 9391-0",
    email: "info@deignis.de",
    web: "https://www.deignis.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 4,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Egenhausen im Nordschwarzwald, Klinikabteilungen in Egenhausen und Altensteig.",
    fokus: "Stationäre medizinische Rehabilitation bei psychosomatischen und psychischen Erkrankungen auf christlicher Basis.",
    facts: ["DRV-Kennziffer A23492 laut Klinikseite.", "Behandlungsdauer 4–6 Wochen laut Trägerseite.", "Klinikkompass-Liste psychosomatischer Reha."],
  },
  {
    id: "ck-curtius",
    name: "Curtius Klinik",
    short: "Curtius Klinik",
    city: "Malente",
    plz: "23714",
    street: "Neue Kampstraße 2",
    st: "SH",
    traeger: "Curtius Klinik GmbH & Co. KG",
    art: "privat",
    phone: "04523 407-0",
    email: "info@curtius-klinik.de",
    web: "https://www.curtius-klinik.de",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Bad Malente-Gremsmühlen, Holsteinische Schweiz, Seelage.",
    fokus: "Fachklinik für psychosomatische Medizin und Psychotherapie, inkl. Essstörungen.",
    facts: ["Klinikkompass-Liste psychosomatischer Reha.", "Nicht identisch mit der Mühlenbergklinik am Ort.", "Stationäre Rehabilitation."],
  },
  {
    id: "ck-birkental",
    name: "Kliniken Hartenstein – Klinik Birkental",
    short: "Klinik Birkental",
    city: "Bad Wildungen",
    plz: "34537",
    street: "Zur Herche 2",
    st: "HE",
    traeger: "Kliniken Hartenstein GmbH & Co. KG",
    art: "privat",
    phone: "05621 76-0",
    email: "verwaltung-birkental@kliniken-hartenstein.de",
    web: "https://www.kliniken-hartenstein.de/psychosomatik/",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Bad Wildungen-Reinhardshausen, Nordhessen.",
    fokus: "Fachklinik für psychosomatische Rehabilitation neben Orthopädie.",
    facts: ["Eigene Chefärztin Psychosomatik laut Klinikseite.", "Nicht identisch mit Parkland, Homberg oder MEDICLIN Bad Wildungen.", "AHB und Heilverfahren."],
  },
  {
    id: "ck-griesbacherhof",
    name: "Johannesbad Fachklinik Griesbacherhof",
    short: "Griesbacherhof",
    city: "Bad Griesbach",
    plz: "94086",
    street: "Griesbacherhof 1",
    st: "BY",
    traeger: "Johannesbad Gruppe",
    art: "privat",
    phone: "08532 22-0",
    web: "https://www.johannesbad.de/",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Bad Griesbach in Niederbayern.",
    fokus: "Psychosomatische Rehabilitation der Johannesbad Gruppe.",
    facts: ["Anderes Haus als Furth, Holthausen, Fredeburg und Raupennest.", "Kurortlage.", "AHB und Heilverfahren."],
  },
  {
    id: "ck-sieg-reha",
    name: "Sieg Reha Hennef",
    short: "Sieg Reha",
    city: "Hennef",
    plz: "53773",
    street: "Mittelstraße 49-51",
    st: "NW",
    traeger: "Sieg Reha GmbH",
    art: "privat",
    phone: "02242 96988-0",
    email: "info@siegreha.de",
    web: "https://siegreha.de/service/psychosomatische-rehabilitation/",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 6,
    gender: "gemischt",
    setting: "tagesklinik",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Hennef an der Sieg, Mittelstraße; zweiter Standort Alfter.",
    fokus: "Ganztägig ambulante psychosomatische Rehabilitation.",
    facts: ["Klinikkompass-Liste psychosomatischer Reha.", "Nicht identisch mit der Eschenberg-Wildpark-Klinik am Ort.", "Setting ganztägig ambulant."],
  },
  {
    id: "ck-hoechsten",
    name: "Fachklinik Höchsten",
    short: "Höchsten",
    city: "Bad Saulgau",
    plz: "88348",
    street: "Sonnenhof 1",
    st: "BW",
    traeger: "Die Zieglerschen",
    art: "kirche",
    phone: "07581 20290-0",
    email: "willkommen-hoechsten@zieglersche.de",
    web: "https://www.zieglersche.de/hoechsten",
    kind: "sucht",
    alk: true,
    drog: true,
    med: true,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "frauen",
    setting: "stationaer",
    ahb: false,
    hv: true,
    bar: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "einbett-mehrheit",
    lage: "Im Kurgebiet von Bad Saulgau, Oberschwaben.",
    fokus: "Frauenspezifische stationäre Entwöhnung bei Abhängigkeitserkrankungen.",
    facts: ["Zieglersche Suchthilfe, eines der ältesten Frauenhäuser der Sucht-Reha.", "LSS-BW-Liste stationärer Entwöhnung.", "Barrierefreie Nutzung aller Räume laut Trägerseite."],
  },
  {
    id: "ck-brueckle",
    name: "Therapiezentrum Brückle",
    short: "Brückle",
    city: "Buggingen",
    plz: "79426",
    street: "Alter Brückleweg 12",
    st: "BW",
    traeger: "Arbeitskreis Rauschmittel Lörrach e.V.",
    art: "gemeinnuetzig",
    phone: "07631 93626-0",
    email: "verwaltung@therapiezentrum-brueckle.de",
    web: "https://www.therapiezentrum-brueckle.de",
    kind: "sucht",
    alk: false,
    drog: true,
    med: false,
    glueck: false,
    subst: true,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 26,
    gender: "maenner",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Am Rand von Buggingen, 25 km südlich von Freiburg, Markgräflerland.",
    fokus: "Stationäre medizinische Rehabilitation für Männer mit Abhängigkeit von Opiaten, THC und Partydrogen.",
    facts: ["BtMG-Anerkennung, QMS-Reha laut Jahresbericht.", "LSS-BW-Liste.", "Adaption im Rehahaus Gundelfingen ist ein anderes Haus."],
  },
  {
    id: "ck-rehahaus-gundelfingen",
    name: "Rehahaus Gundelfingen",
    short: "Rehahaus Gundelfingen",
    city: "Gundelfingen",
    plz: "79194",
    street: "Gewerbestraße 6",
    st: "BW",
    traeger: "Arbeitskreis Rauschmittel Lörrach e.V.",
    art: "gemeinnuetzig",
    phone: "0761 584873",
    email: "verwaltung-rhg@rehahaus-gundelfingen.de",
    web: "https://www.therapiezentrum-brueckle.de",
    kind: "sucht",
    alk: false,
    drog: true,
    med: false,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "adaption",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Gundelfingen nördlich von Freiburg.",
    fokus: "Adaptionsphase nach der Entwöhnung im Therapiezentrum Brückle.",
    facts: ["Träger AKRM Lörrach e.V.", "QMS-Reha gemeinsam mit Brückle.", "Adaption, nicht die Intensivphase in Buggingen."],
  },
  {
    id: "ck-ebhausen",
    name: "Lebenszentrum Ebhausen",
    short: "Ebhausen",
    city: "Ebhausen",
    plz: "72224",
    street: "Carl-Schickhardt-Straße 27",
    st: "BW",
    traeger: "Lebenszentrum Ebhausen e.V.",
    art: "gemeinnuetzig",
    phone: "07458 9992-0",
    email: "info@lz-ebhausen.de",
    web: "https://www.lebenszentrum-ebhausen.de",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "frauen",
    setting: "adaption",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Ebhausen im Nordschwarzwald.",
    fokus: "Stationäre Suchtrehabilitation / Adaption für Frauen laut LSS-BW.",
    facts: ["LSS-BW-Liste stationärer Einrichtungen.", "Frauenspezifisch.", "Träger Lebenszentrum Ebhausen e.V."],
  },
  {
    id: "ck-schloz",
    name: "bwlv Fachklinik Schloz",
    short: "Schloz",
    city: "Freudenstadt",
    plz: "72250",
    street: "Ikarusweg 14",
    st: "BW",
    traeger: "Baden-Württembergischer Landesverband für Prävention und Rehabilitation",
    art: "gemeinnuetzig",
    phone: "07441 9195050",
    email: "schloz@bw-lv.de",
    web: "https://www.bw-lv.de/behandlung/stationaere-angebote-und-fachkliniken/fachklinik-schloz/",
    kind: "sucht",
    alk: true,
    drog: false,
    med: true,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "frauen",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Am Stadtrand des Luftkurorts Freudenstadt, parkähnlicher Garten.",
    fokus: "Frauenspezifische Entwöhnung bei Alkohol- und Medikamentenabhängigkeit.",
    facts: ["bwlv-Trägerseite: besondere Klinik für Frauen.", "LSS-BW-Liste.", "Umzug nach Renchen für 28.09.2026 auf der Trägerseite angekündigt; Standort bleibt bis dahin Freudenstadt."],
  },
  {
    id: "ck-zwieselberg",
    name: "Fachklinik Zwieselberg",
    short: "Zwieselberg",
    city: "Freudenstadt",
    plz: "72250",
    street: "Zwieselberg 9",
    st: "BW",
    traeger: "Fachklinik Zwieselberg",
    art: "gemeinnuetzig",
    phone: "07441 2205",
    email: "info@fachklinik-zwieselberg.de",
    web: "https://www.fachklinik-zwieselberg.de",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "maenner",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Zwieselberg bei Freudenstadt, Nordschwarzwald.",
    fokus: "Stationäre Entwöhnung für Männer laut LSS-BW.",
    facts: ["LSS-BW-Liste stationärer Entwöhnung.", "Männerspezifisch.", "Nicht identisch mit Fachklinik Schloz oder Wiesengrund."],
  },
  {
    id: "ck-bwlv-wiesengrund",
    name: "bwlv Fachklinik Wiesengrund",
    short: "Wiesengrund Kniebis",
    city: "Freudenstadt",
    plz: "72250",
    street: "Ellbachseeweg 1-5",
    st: "BW",
    traeger: "Baden-Württembergischer Landesverband für Prävention und Rehabilitation",
    art: "gemeinnuetzig",
    phone: "07442 83786-0",
    email: "wiesengrund@bw-lv.de",
    web: "https://www.bw-lv.de/fachkliniken/fachklinik-wiesengrund/",
    kind: "sucht",
    alk: false,
    drog: true,
    med: false,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 26,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Freudenstadt-Kniebis, Nordschwarzwald.",
    fokus: "Stationäre Entwöhnung bei Drogenabhängigkeit inkl. Adaption.",
    facts: ["bwlv, BtMG-anerkannt.", "Jahresbericht 2025 nennt 54 Betten.", "LSS-BW-Liste."],
  },
  {
    id: "ck-fischer-haus",
    name: "Fachklinik Fischer-Haus",
    short: "Fischer-Haus",
    city: "Gaggenau",
    plz: "76571",
    street: "Mönchkopfstraße 21",
    st: "BW",
    traeger: "Fischer-Haus e.V.",
    art: "gemeinnuetzig",
    phone: "07225 9744-0",
    email: "info@fischer-haus.de",
    web: "https://www.fischer-haus.de",
    kind: "sucht",
    alk: false,
    drog: true,
    med: false,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "maenner",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Gaggenau-Michelbach, Nordschwarzwald.",
    fokus: "Stationäre Entwöhnung für Männer mit Drogenabhängigkeit, inkl. besonderer sozialer Belastung.",
    facts: ["LSS-BW- und BtMG-Liste.", "Männerspezifisch.", "Nicht identisch mit Rehaklinik Freiolsheim am Ort."],
  },
  {
    id: "ck-muenzesheim",
    name: "Therapiezentrum Münzesheim",
    short: "Münzesheim",
    city: "Kraichtal",
    plz: "76703",
    street: "Am Mühlberg 1",
    st: "BW",
    traeger: "Evangelische Stadtmission Heidelberg",
    art: "kirche",
    phone: "07250 600",
    email: "info@kraichtal-kliniken.de",
    web: "https://www.kraichtal-kliniken.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "maenner",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Kraichtal-Münzesheim.",
    fokus: "Stationäre Entwöhnung für Männer im Verbund der Kraichtal-Kliniken.",
    facts: ["LSS-BW-Liste.", "Nicht identisch mit Haus Kraichtalblick (Frauen) am selben Träger.", "Evangelische Stadtmission Heidelberg."],
  },
  {
    id: "ck-birkenbuck",
    name: "Rehaklinik Birkenbuck",
    short: "Birkenbuck",
    city: "Malsburg-Marzell",
    plz: "79429",
    street: "Birkenbuck 4",
    st: "BW",
    traeger: "Rehaklinik Birkenbuck",
    art: "gemeinnuetzig",
    phone: "07626 902-100",
    email: "info@rehaklinik-birkenbuck.de",
    web: "https://www.rehaklinik-birkenbuck.de",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "frauen",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: true,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Malsburg-Marzell, Südschwarzwald, Lage Birkenbuck.",
    fokus: "Frauenspezifische stationäre Suchtrehabilitation laut LSS-BW.",
    facts: ["LSS-BW-Liste.", "Nicht identisch mit Rehaklinik Kandertal am selben Ort.", "Frauenspezifisch."],
  },
  {
    id: "ck-schielberg",
    name: "bwlv Fachklinik Schielberg",
    short: "Schielberg",
    city: "Marxzell",
    plz: "76359",
    street: "Waldstraße 32",
    st: "BW",
    traeger: "Baden-Württembergischer Landesverband für Prävention und Rehabilitation",
    art: "gemeinnuetzig",
    phone: "07248 9173-0",
    email: "schielberg@bw-lv.de",
    web: "https://www.bw-lv.de/behandlung/stationaere-angebote-und-fachkliniken/fachklinik-schielberg/",
    kind: "sucht",
    alk: false,
    drog: true,
    med: false,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Marxzell-Schielberg, Nordschwarzwald.",
    fokus: "Stationäre Kurzzeittherapie für Drogenabhängige.",
    facts: ["bwlv, BtMG-anerkannt.", "Umzug nach Wiesloch für Oktober 2026 auf der Trägerseite angekündigt; Standort bleibt bis dahin Schielberg.", "LSS-BW-Liste."],
  },
  {
    id: "ck-bassum",
    name: "Fachklinik Bassum",
    short: "Bassum",
    city: "Bassum",
    plz: "27211",
    street: "Marie-Hackfeld-Straße 6",
    st: "NI",
    traeger: "Stiftung Bethel",
    art: "kirche",
    phone: "04241 803000",
    email: "mail.fachklinikbassum@bethel.de",
    web: "https://www.fachklinik-bassum.de/",
    kind: "sucht",
    alk: true,
    drog: false,
    med: true,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "beides",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Direkt auf dem Gelände des Bassumer Krankenhauses, Städtedreieck Bremen–Hannover–Osnabrück.",
    fokus: "Stationäre und tagesklinische Rehabilitation bei Alkohol- und Medikamentenabhängigkeit.",
    facts: ["Stiftung Bethel.", "DHS-Suchthilfeverzeichnis.", "Seit 2008 am Standort, QS-Programm der DRV laut Klinikseite."],
  },
  {
    id: "ck-stillenberg",
    name: "LWL-Rehabilitationszentrum Südwestfalen – Fachklinik Stillenberg",
    short: "Stillenberg",
    city: "Warstein",
    plz: "59581",
    street: "Franz-Hegemann-Straße 23",
    st: "NW",
    traeger: "Landschaftsverband Westfalen-Lippe",
    art: "gemeinnuetzig",
    phone: "02902 82-2010",
    email: "info@lwl-rehabilitation-suedwestfalen.de",
    web: "https://www.lwl-klinik-warstein.de",
    kind: "sucht",
    alk: true,
    drog: true,
    med: true,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: true,
    jung: false,
    room: "unbekannt",
    lage: "LWL-Gelände Warstein, Sauerland.",
    fokus: "Stationäre Entwöhnung bei Alkohol, Drogen und Medikamenten, inkl. komorbider psychischer Erkrankungen.",
    facts: ["DHS-Suchthilfeverzeichnis; Bundesverband Suchthilfe.", "110 Plätze laut therapieplaetze.de.", "Nicht das LWL-Institut für Rehabilitation (RPK) am selben Gelände."],
  },
  {
    id: "ck-briese",
    name: "Fachklinik Briese",
    short: "Briese",
    city: "Birkenwerder",
    plz: "16547",
    street: "Briese 1-2",
    st: "BB",
    traeger: "ADV Rehabilitation und Integration gGmbH",
    art: "gemeinnuetzig",
    phone: "03303 5797-100",
    email: "aufnahme.briese@adv-suchthilfe.de",
    web: "https://www.adv-suchthilfe.de/fachkliniken/fachklinik-briese/",
    kind: "sucht",
    alk: true,
    drog: true,
    med: true,
    glueck: true,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Am Briesesee in Birkenwerder OT Briese, Landschaftsschutzgebiet, S-Bahn nach Berlin.",
    fokus: "Stationäre Entwöhnung bei Drogen- und Alkoholabhängigkeit.",
    facts: ["DRV Bund federführend, BtMG §§ 35/36 laut Trägerseite.", "DHS-Suchthilfeverzeichnis.", "Nicht identisch mit Tannenhof Berlin-Brandenburg am Ort."],
  },
  {
    id: "ck-adaption-birkenwerder",
    name: "ADV Adaptionshaus Birkenwerder",
    short: "Adaption Birkenwerder",
    city: "Birkenwerder",
    plz: "16547",
    street: "Bergfelder Straße 10",
    st: "BB",
    traeger: "ADV Rehabilitation und Integration gGmbH",
    art: "gemeinnuetzig",
    phone: "03303 5797-000",
    email: "aufnahme.adh@adv-suchthilfe.de",
    web: "https://www.adv-suchthilfe.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "adaption",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Birkenwerder, Bergfelder Straße, S-Bahn S1.",
    fokus: "Adaption nach stationärer Entwöhnung der Fachklinik Briese.",
    facts: ["Gleicher Träger wie Fachklinik Briese, anderes Haus.", "DRV- und GKV-Anerkennung laut Trägerseite.", "Setting Adaption."],
  },
  {
    id: "ck-adv-f42",
    name: "Fachklinik F42",
    short: "F42",
    city: "Berlin",
    plz: "12053",
    street: "Flughafenstraße 42",
    st: "BE",
    traeger: "ADV Rehabilitation und Integration gGmbH",
    art: "gemeinnuetzig",
    phone: "030 55443-5300",
    email: "aufnahme@adv-suchthilfe.de",
    web: "https://www.adv-suchthilfe.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Berlin-Neukölln, Flughafenstraße, U-Bahn Boddinstraße.",
    fokus: "Stationäre Entwöhnungsbehandlung der ADV Suchthilfe in Berlin.",
    facts: ["ADV Rehabilitation und Integration gGmbH.", "Anderes Haus als Fachklinik Briese.", "Öffentliche Trägerseite."],
  },
  {
    id: "ck-medbo-woellershof",
    name: "medbo Fachklinik zur Rehabilitation bei Abhängigkeitserkrankungen Wöllershof",
    short: "medbo Wöllershof",
    city: "Störnstein",
    plz: "92721",
    street: "Wöllershof 1",
    st: "BY",
    traeger: "medbo KU",
    art: "gemeinnuetzig",
    phone: "09602 780",
    web: "https://www.medbo.de/kliniken-einrichtungen/psychiatrie-psychotherapie/klinik-fuer-psychiatrie-psychosomatik-psychotherapie-woellershof/sucht-rehabilitation",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Wöllershof, Gemeinde Störnstein, Oberpfalz.",
    fokus: "Medizinische Rehabilitation bei Abhängigkeitserkrankungen am Bezirksklinikum Wöllershof.",
    facts: ["DHS-Suchthilfeverzeichnis.", "medbo, Kommunalunternehmen.", "Auftrag ist Sucht-Rehabilitation, nicht die Akutpsychiatrie."],
  },
  {
    id: "ck-haus-lenne",
    name: "Haus Lenné",
    short: "Haus Lenné",
    city: "Berlin",
    plz: "14089",
    street: "Breitehornweg 51-54",
    st: "BE",
    traeger: "Lenné gGmbH",
    art: "gemeinnuetzig",
    phone: "030 841898-10",
    email: "aufnahme@haus-lenne.de",
    web: "https://www.haus-lenne.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "beides",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Berlin-Spandau (Gatow/Kladow) am Havelrand.",
    fokus: "Kombitherapie aus stationärer und ambulanter Phase plus interne Adaption.",
    facts: ["Q-Reha+-zertifiziert, seit 1996.", "DHS-Suchthilfeverzeichnis.", "Nicht identisch mit MEDIAN Berlin-Kladow."],
  },
  {
    id: "ck-median-adaption-koeln",
    name: "MEDIAN Adaptionshaus Köln",
    short: "Adaption Köln",
    city: "Köln",
    plz: "50827",
    street: "Mathias-Brüggen-Straße 17",
    st: "NW",
    traeger: "MEDIAN Kliniken",
    art: "privat",
    phone: "0221 95665110",
    web: "https://www.median-kliniken.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "adaption",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Köln-Ehrenfeld, Mathias-Brüggen-Straße.",
    fokus: "Adaption nach stationärer Entwöhnung im MEDIAN-Verbund.",
    facts: ["DHS-Suchthilfeverzeichnis.", "Setting Adaption.", "Nicht identisch mit MEDIAN Dormagen."],
  },
  {
    id: "ck-oberberg-hornberg",
    name: "Oberberg Fachklinik Schwarzwald",
    short: "Oberberg Schwarzwald",
    city: "Hornberg",
    plz: "78132",
    street: "Oberberg 1",
    st: "BW",
    traeger: "Oberberg Kliniken",
    art: "privat",
    phone: "07833 792-0",
    email: "info@oberbergkliniken.de",
    web: "https://www.oberbergkliniken.de/",
    kind: "psychosomatik",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 5,
    dmax: 8,
    gender: "gemischt",
    setting: "stationaer",
    ahb: true,
    hv: true,
    kinder: false,
    trauma: true,
    jung: false,
    room: "unbekannt",
    lage: "Hornberg im Schwarzwald, Kliniklage Oberberg.",
    fokus: "Private Fachklinik für Psychosomatik, Psychiatrie und Abhängigkeitserkrankungen.",
    facts: ["LSS-BW führt das Haus unter stationärer Suchtbehandlung.", "Anderer Standort als Oberberg Berlin-Brandenburg.", "Öffentliche Trägerseite Oberberg."],
  },
  {
    id: "ck-ringgenhof",
    name: "Fachklinik Ringgenhof",
    short: "Ringgenhof",
    city: "Wilhelmsdorf",
    plz: "88271",
    street: "Riedhauser Straße 61",
    st: "BW",
    traeger: "Die Zieglerschen",
    art: "kirche",
    phone: "07503 920-0",
    web: "https://www.zieglersche.de/ringgenhof",
    kind: "sucht",
    alk: true,
    drog: true,
    med: true,
    glueck: true,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 26,
    gender: "maenner",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Wilhelmsdorf bei Ravensburg, Oberschwaben.",
    fokus: "Männerspezifische Entwöhnung: Abteilungen Alkohol/Glücksspiel, Drogen sowie Sucht mit Psychose.",
    facts: ["Zieglersche Suchthilfe, Männerklinik seit über 50 Jahren.", "Nicht identisch mit Fachklinik Höchsten (Frauen) desselben Trägers.", "Destatis-Verzeichnis der Rehabilitationseinrichtungen 2023."],
  },
  {
    id: "ck-renchtal",
    name: "bwlv Fachklinik Haus Renchtal",
    short: "Haus Renchtal",
    city: "Renchen",
    plz: "77871",
    street: "Renchtalstraße 14",
    st: "BW",
    traeger: "Baden-Württembergischer Landesverband für Prävention und Rehabilitation",
    art: "gemeinnuetzig",
    phone: "07843 949-0",
    email: "renchtal@bw-lv.de",
    web: "https://www.bw-lv.de/behandlung/stationaere-angebote-und-fachkliniken/fachklinik-haus-renchtal/",
    kind: "sucht",
    alk: true,
    drog: false,
    med: true,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Renchen im Renchtal, Ortenau.",
    fokus: "Rehabilitation bei Alkohol- und Medikamentenabhängigkeit.",
    facts: ["bwlv-Trägerseite.", "Zentrale Telefonnummer 07843 949-0 laut Klinikseite.", "Fusion mit Fachklinik Schloz für 28.09.2026 angekündigt; Haus bleibt bis dahin eigenständig."],
  },
  {
    id: "ck-hochstadt",
    name: "Bezirksklinik Hochstadt",
    short: "Hochstadt",
    city: "Hochstadt am Main",
    plz: "96272",
    street: "Hauptstraße 13",
    st: "BY",
    traeger: "Gesundheitseinrichtungen des Bezirks Oberfranken",
    art: "gemeinnuetzig",
    phone: "09574 6337-0",
    email: "hochstadt@gebo-med.de",
    web: "https://www.gebo-med.de/standorte/bezirksklinik-hochstadt",
    kind: "sucht",
    alk: true,
    drog: true,
    med: true,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 26,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Ortsmitte von Hochstadt am Main, Bahnstation Hochstadt/Marktzeuln.",
    fokus: "Vollstationäre Rehabilitation für Drogen-, Medikamenten- und Alkoholabhängige nach abgeschlossenem Entzug.",
    facts: ["gebo, 75 Planbetten laut Klinikseite.", "Entwöhnung und Adaption am Standort.", "Nicht die Akutentzugsstationen in Bayreuth oder Ebensfeld."],
  },
  {
    id: "ck-nettetal",
    name: "Fachklinik Nettetal",
    short: "Nettetal",
    city: "Wallenhorst",
    plz: "49134",
    street: "Hohnweg 2",
    st: "NI",
    traeger: "CRT Caritas Reha und Teilhabe GmbH",
    art: "kirche",
    phone: "0541 40892-0",
    email: "aufnahme@fk-nettetal.de",
    web: "https://www.fachklinik-nettetal.de/",
    kind: "dual",
    alk: true,
    drog: true,
    med: true,
    glueck: false,
    subst: true,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 24,
    gender: "maenner",
    setting: "beides",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Am Ortsrand von Wallenhorst nördlich von Osnabrück.",
    fokus: "Stationäre Entwöhnung und integrierte Adaption für Männer, inkl. Psychose und Sucht.",
    facts: ["Caritas, federführend DRV Braunschweig-Hannover.", "BtMG-Anerkennung, Kombi-Nord.", "Männerspezifisch."],
  },
  {
    id: "ck-oerrel",
    name: "Fachklinik Oerrel / Haus Niedersachsen",
    short: "Oerrel",
    city: "Dedelstorf",
    plz: "29386",
    street: "Feldstraße 5",
    st: "NI",
    traeger: "Haus Niedersachsen gGmbH",
    art: "gemeinnuetzig",
    phone: "05832 82-0",
    email: "oerrel@haus-niedersachsen.de",
    web: "https://www.haus-niedersachsen.de/fachklinik-oerrel/",
    kind: "sucht",
    alk: true,
    drog: false,
    med: true,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 6,
    dmax: 13,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Campus in der südlichen Lüneburger Heide, Ortsteil Oerrel der Gemeinde Dedelstorf.",
    fokus: "Stationäre beruflich orientierte Entwöhnung bei Alkohol- und Medikamentenabhängigkeit.",
    facts: ["Seit 1973 Suchtfachklinik.", "Kombi-Nord mit achtwöchigem stationärem Modul.", "GSB-Qualitätssiegel REHA laut Trägerseite."],
  },
  {
    id: "ck-oldenburger-land",
    name: "Fachklinik Oldenburger Land",
    short: "Oldenburger Land",
    city: "Dötlingen",
    plz: "27801",
    street: "Neerstedter Straße 9",
    st: "NI",
    traeger: "Diakonisches Werk Oldenburg",
    art: "kirche",
    phone: "04432 9480-0",
    web: "https://www.fachklinik-oldenburger-land.de/",
    kind: "dual",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Dötlingen-Neerstedt im Oldenburger Land.",
    fokus: "Stationäre Langzeitentwöhnung für Menschen mit Suchterkrankung und intellektueller Beeinträchtigung.",
    facts: ["Diakonie Oldenburg.", "Bundesverband Suchthilfe.", "Mitbehandlung komorbider psychischer Störungen laut Trägerseite."],
  },
  {
    id: "ck-lago",
    name: "Fachklinik LAGO",
    short: "LAGO",
    city: "Berlin",
    plz: "14109",
    street: "Am Großen Wannsee 29-31",
    st: "BE",
    traeger: "Drogentherapie-Zentrum Berlin gGmbH",
    art: "gemeinnuetzig",
    phone: "030 806884-0",
    email: "lago@dtz-berlin.de",
    web: "https://www.berlin-suchthilfe.de/einrichtungen/fachklinik-lago",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 26,
    gender: "gemischt",
    setting: "beides",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Direkt am Großen Wannsee in Berlin-Zehlendorf.",
    fokus: "Stationäre medizinische Rehabilitation bei Drogen-, Alkohol- und Medikamentenabhängigkeit.",
    facts: ["Drogentherapie-Zentrum Berlin.", "Kurzzeit, Langzeit und Adaption auf dem Gelände.", "Paritätisches Qualitätssiegel laut Trägerseite."],
  },
  {
    id: "ck-saaletalklinik",
    name: "Saaletalklinik",
    short: "Saaletalklinik",
    city: "Bad Neustadt an der Saale",
    plz: "97616",
    street: "Salzburgweg 7",
    st: "BY",
    traeger: "Haus Saaletal GmbH",
    art: "privat",
    phone: "09771 905-0",
    email: "stk@saaletalklinik.de",
    web: "https://saaletal.campus-nes.de/",
    kind: "sucht",
    alk: true,
    drog: false,
    med: true,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 15,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Am Salzburgweg in Bad Neustadt an der Fränkischen Saale, Campus NES.",
    fokus: "Stationäre medizinische Rehabilitation bei Alkohol- und Medikamentenabhängigkeit.",
    facts: ["Fachverband Sucht-Mitglied.", "Kombitherapie mit achtwöchiger stationärer Phase.", "Nicht identisch mit Klinik Neumühle."],
  },
  {
    id: "ck-neumuehle",
    name: "Klinik Neumühle",
    short: "Neumühle",
    city: "Hollstadt",
    plz: "97618",
    street: "Neumühle 3",
    st: "BY",
    traeger: "Haus Saaletal GmbH",
    art: "privat",
    phone: "09773 9150-0",
    web: "https://www.klinik-neumuehle.de/",
    kind: "sucht",
    alk: true,
    drog: true,
    med: true,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 22,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Hollstadt bei Bad Neustadt an der Saale, Unterfranken.",
    fokus: "Stationäre Entwöhnung vor allem bei Drogenabhängigkeit, inkl. frauenspezifischem Angebot.",
    facts: ["Schwesterklinik der Saaletalklinik.", "Versorgungsvertrag § 111 SGB V laut Trägerseite.", "Q Reha plus."],
  },
  {
    id: "ck-bwlv-tuebingen",
    name: "bwlv Fachklinik Tübingen",
    short: "Tübingen bwlv",
    city: "Tübingen",
    plz: "72072",
    street: "Bläsiberg 1",
    st: "BW",
    traeger: "Baden-Württembergischer Landesverband für Prävention und Rehabilitation",
    art: "gemeinnuetzig",
    phone: "07071 9266-0",
    email: "fachklinik.tuebingen@bw-lv.de",
    web: "https://www.bw-lv.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 26,
    gender: "gemischt",
    setting: "beides",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Am Bläsiberg in Tübingen.",
    fokus: "Stationäre Intensivtherapie und Adaption für drogen- und alkoholabhängige Erwachsene.",
    facts: ["bwlv, BtMG-anerkannt.", "Landesstelle BW führt das Haus.", "Nicht die Universitätsklinik für Psychiatrie."],
  },
  {
    id: "ck-hausen-im-tal",
    name: "Therapiezentrum Hausen im Tal",
    short: "Hausen im Tal",
    city: "Leibertingen",
    plz: "88637",
    street: "Voradelberg 2",
    st: "BW",
    traeger: "Therapiezentrum Hausen im Tal gGmbH",
    art: "gemeinnuetzig",
    phone: "07575 925020",
    email: "info@tzhit.de",
    web: "https://www.tzhit.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: true,
    room: "unbekannt",
    lage: "Leibertingen-Thalheim / Hausen im Tal an der oberen Donau.",
    fokus: "Stationäre Suchttherapie für junge Erwachsene.",
    facts: ["Landesstelle BW als Fachklinik mit DRV-Belegung.", "BtMG-Anerkennung laut Landesliste.", "Schwerpunkt junge Erwachsene."],
  },
  {
    id: "ck-boerstingen",
    name: "Reha-Einrichtung Schloss Börstingen",
    short: "Schloss Börstingen",
    city: "Starzach",
    plz: "72181",
    street: "Rottenburger Straße 6",
    st: "BW",
    traeger: "mevesta e.V.",
    art: "gemeinnuetzig",
    phone: "07031 2181-430",
    email: "reha-boerstingen@mevesta.de",
    web: "https://www.mevesta.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: true,
    room: "unbekannt",
    lage: "Schloss Börstingen in Starzach an der Neckar-Alb.",
    fokus: "Stationäre medizinische Rehabilitation für junge Erwachsene mit Drogen- und Alkoholabhängigkeit.",
    facts: ["Hauptbeleger DRV Baden-Württemberg.", "Anerkennung nach §§ 35/36 BtMG.", "Zielgruppe ca. 17–30 Jahre laut Trägerseite."],
  },
  {
    id: "ck-adaption-lahr",
    name: "Integrationszentrum Lahr",
    short: "Adaption Lahr",
    city: "Lahr",
    plz: "77933",
    street: "Brestenbergstraße 2-4",
    st: "BW",
    traeger: "AGJ Fachverband Freiburg",
    art: "kirche",
    phone: "07821 92280-0",
    email: "adaption-lahr@agj-freiburg.de",
    web: "https://www.adaption-lahr.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "adaption",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Lahr/Schwarzwald, städtische Adaption der Rehaklinik Freiolsheim.",
    fokus: "Stationäre Adaption nach Entwöhnung.",
    facts: ["Externe Adaption der Rehaklinik Freiolsheim, eigener Stadtstandort.", "AGJ Freiburg.", "DRV Baden-Württemberg laut Landesstelle."],
  },
  {
    id: "ck-fuerstenwald",
    name: "Fachklinik Fürstenwald",
    short: "Fürstenwald",
    city: "Calden",
    plz: "34379",
    street: "Grundweg 2-4",
    st: "HE",
    traeger: "Hephata Diakonie",
    art: "kirche",
    phone: "05609 629-0",
    email: "fachklinik.fuerstenwald@hephata.de",
    web: "https://www.hephata.de/hilfe-rat/fachklinik-/-stationaere-therapie/fachklinik-fuerstenwald",
    kind: "sucht",
    alk: true,
    drog: false,
    med: true,
    glueck: true,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: true,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Calden-Fürstenwald nordwestlich von Kassel, Parkanlage.",
    fokus: "Stationäre Langzeitentwöhnung bei Alkohol-, Medikamenten- und Mehrfachabhängigkeit.",
    facts: ["Hephata Diakonie, DeQus.", "Nicht identisch mit Fachklinik Weibersbrunn desselben Trägers.", "Kita auf dem Gelände laut Trägerseite."],
  },
  {
    id: "ck-neue-rhoen",
    name: "Fachklinik Neue Rhön",
    short: "Neue Rhön",
    city: "Burghaun",
    plz: "36151",
    street: "Mahlertshof 4",
    st: "HE",
    traeger: "GBBS gGmbH",
    art: "gemeinnuetzig",
    phone: "06652 991-0",
    email: "info@neue-rhoen.de",
    web: "https://neue-rhoen.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: true,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Am Mahlertshof am Rand der Rhön bei Burghaun, Landkreis Fulda.",
    fokus: "Suchtfachklinik mit Paartherapie und Mitaufnahme von Begleitkindern.",
    facts: ["Medizinische Rehabilitation nach SGB IX für DRV und GKV.", "Familienzimmer vorhanden laut Trägerseite.", "Nicht identisch mit der DRV-Klinik Hartwald."],
  },
  {
    id: "ck-birkenweg",
    name: "Fachklinik Am Birkenweg",
    short: "Am Birkenweg",
    city: "Darmstadt",
    plz: "64295",
    street: "Birkenweg 17",
    st: "HE",
    traeger: "Caritasverband Darmstadt e.V.",
    art: "kirche",
    phone: "06151 13037-0",
    email: "tagesrehabilitation@caritas-darmstadt.de",
    web: "https://www.tagesrehabilitation.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "tagesklinik",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Darmstadt, etwa zehn Gehminuten vom Hauptbahnhof.",
    fokus: "Ganztägig ambulante Entwöhnung bei Alkohol, Drogen und Medikamenten.",
    facts: ["Caritas Darmstadt, Schwesterhaus der Klinik Schloss Falkenhof.", "Setting Tagesklinik.", "DeQus und ISO 9001 laut Trägerseite."],
  },
  {
    id: "ck-adaption-heppenheim",
    name: "Adaptionseinrichtung An der Bergstraße",
    short: "Adaption Heppenheim",
    city: "Heppenheim",
    plz: "64646",
    street: "Kalterer Straße 3",
    st: "HE",
    traeger: "Caritasverband Darmstadt e.V.",
    art: "kirche",
    web: "https://www.caritas-darmstadt.de/beratung-und-hilfe/hilfebeisucht/stationaereeinrichtungen/stationaereeinrichtungen",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "adaption",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Heppenheim an der Bergstraße, Fachabteilung der Klinik Schloss Falkenhof.",
    fokus: "Vollstationäre Adaption nach vorangegangener Sucht-Reha.",
    facts: ["Seit 1998 Fachabteilung der Klinik Schloss Falkenhof.", "Getrennt vom Falkenhof-Campus Bensheim.", "Caritas Darmstadt."],
  },
  {
    id: "ck-rusteberg",
    name: "Fachklinik Rusteberg",
    short: "Rusteberg",
    city: "Marth",
    plz: "37318",
    street: "Rusteberger Straße 1",
    st: "TH",
    traeger: "SiT Suchthilfe in Thüringen gGmbH",
    art: "gemeinnuetzig",
    phone: "036081 691-0",
    email: "info@fachklinik-rusteberg.de",
    web: "https://sit-online.org/suchthilfe-aus-einer-hand/fachklinik-rusteberg",
    kind: "dual",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 24,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Am Ortsrand von Marth im Eichsfeld, Dreiländereck Thüringen–Niedersachsen–Hessen.",
    fokus: "Stationäre medizinische Reha vor allem für Drogenabhängige mit Mitbehandlung psychischer Komorbidität.",
    facts: ["SiT Thüringen, federführend DRV Mitteldeutschland.", "ISO/deQus.", "Geschlechtsspezifische Gruppen laut Trägerseite."],
  },
  {
    id: "ck-adaption-erfurt",
    name: "Adaptionseinrichtung Erfurt",
    short: "Adaption Erfurt",
    city: "Erfurt",
    plz: "99096",
    street: "Arndtstraße 2",
    st: "TH",
    traeger: "SiT Suchthilfe in Thüringen gGmbH",
    art: "gemeinnuetzig",
    phone: "0361 26289774",
    email: "adaption@sit-online.org",
    web: "https://sit-online.org/suchthilfe-aus-einer-hand/adaptionseinrichtungen/adaptionseinrichtung-erfurt",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "adaption",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Erfurt, Neubau mit Einzelzimmern und Gemeinschaftsküchen.",
    fokus: "Stationäre Adaption als zweite Phase nach Langzeittherapie.",
    facts: ["SiT Thüringen.", "Federführend DRV Mitteldeutschland.", "BtMG §§ 35/36 möglich laut Trägerseite."],
  },
  {
    id: "ck-adaption-weimar",
    name: "Adaptionseinrichtung Weimar",
    short: "Adaption Weimar",
    city: "Weimar",
    plz: "99425",
    street: "Berkaer Straße 19",
    st: "TH",
    traeger: "SiT Suchthilfe in Thüringen gGmbH",
    art: "gemeinnuetzig",
    phone: "03643 853936",
    web: "https://sit-online.org/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "adaption",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Weimar, städtische Adaption im SiT-Verbund.",
    fokus: "Stationäre Adaption nach Entwöhnung.",
    facts: ["SiT-Einrichtungsverzeichnis.", "Ergänzt die Adaption Erfurt.", "Gemeinnütziger Träger."],
  },
  {
    id: "ck-greifswald",
    name: "Fachklinik Greifswald",
    short: "Greifswald",
    city: "Greifswald",
    plz: "17489",
    street: "Gützkower Landstraße 96",
    st: "MV",
    traeger: "Evangelisches Krankenhaus Bethanien / Johanna-Odebrecht-Stiftung",
    art: "kirche",
    phone: "03834 543-300",
    email: "reha@odebrecht-stiftung.de",
    web: "https://odebrecht-stiftung.de/krankenhaus/rehabilitation/",
    kind: "sucht",
    alk: true,
    drog: false,
    med: true,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Gelände der Odebrecht-Stiftung am Stadtrand von Greifswald.",
    fokus: "Stationäre medizinische Rehabilitation bei Alkohol- und Medikamentenabhängigkeit.",
    facts: ["Neubau 2024, zuvor Fachklinik Gristower Wiek.", "Hauptbeleger DRV Nord.", "QMS Reha laut Trägerseite."],
  },
  {
    id: "ck-diako-breklum",
    name: "DIAKO Nordfriesland – Fachklinik für Rehabilitation",
    short: "DIAKO Breklum",
    city: "Breklum",
    plz: "25821",
    street: "Gammeltoft 8-15",
    st: "SH",
    traeger: "DIAKO Nordfriesland gGmbH",
    art: "kirche",
    phone: "04671 408-4050",
    email: "anmeldung.reha@diako.de",
    web: "https://www.diako-nf.de/unsere-angebote/fachklinik-fuer-rehabilitation/alkohol-medikamente",
    kind: "sucht",
    alk: true,
    drog: true,
    med: true,
    glueck: true,
    subst: true,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 15,
    gender: "gemischt",
    setting: "beides",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: true,
    jung: false,
    room: "unbekannt",
    lage: "Breklum-Riddorf, Nordfriesland, nahe der Nordsee.",
    fokus: "Stationäre, teilstationäre und Kombi-Reha bei Alkohol, Medikamenten, illegalen Drogen, Glücksspiel und Medien.",
    facts: ["DIAKO Nordfriesland.", "Substitutionsgestützte Reha möglich laut Trägerseite.", "Spezialangebote 55+, Paare, frauenspezifisch."],
  },
  {
    id: "ck-do-it",
    name: "Fachklinik DO IT!",
    short: "DO IT! Travemünde",
    city: "Lübeck",
    plz: "23570",
    street: "Mecklenburger Landstraße 60",
    st: "SH",
    traeger: "Therapiehilfe gGmbH",
    art: "gemeinnuetzig",
    phone: "040 2000107070",
    email: "doit-aufnahme@therapiehilfe.de",
    web: "https://www.therapiehilfe.de/standorte/fachklinik-do-it/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 16,
    dmax: 26,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Lübeck-Travemünde an der Ostsee.",
    fokus: "Stationäre Entwöhnung mit Hauptindikation illegale Drogen und Cannabis.",
    facts: ["Therapiehilfeverbund, deQus/BAR.", "BtMG §§ 35/36.", "Anschlussadaption in Hamburg-Eilbek ist ein anderes Haus."],
  },
  {
    id: "ck-do-it-adaption",
    name: "DO IT! Externe Adaption Hamburg",
    short: "DO IT! Adaption",
    city: "Hamburg",
    plz: "22089",
    street: "Hasselbrookstraße 98",
    st: "HH",
    traeger: "Therapiehilfe gGmbH",
    art: "gemeinnuetzig",
    phone: "040 2000107062",
    email: "ea-aufnahme@therapiehilfe.de",
    web: "https://www.therapiehilfe.de/standorte/do-it_externe_adaption/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "adaption",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Hamburg-Eilbek, Hasselbrookstraße.",
    fokus: "Stationäre Adaption mit Schwerpunkt berufliche Reintegration nach Drogenentwöhnung.",
    facts: ["Therapiehilfeverbund.", "Anerkennung DRV Bund und Krankenkassen laut Trägerseite.", "Nicht identisch mit Oldenfelder Tannen."],
  },
  {
    id: "ck-peers-hoop",
    name: "Fachklinik Peers Hoop",
    short: "Peers Hoop",
    city: "Lindewitt",
    plz: "24969",
    street: "Westerstraße 2-4",
    st: "SH",
    traeger: "Therapiehilfe gGmbH",
    art: "gemeinnuetzig",
    phone: "04604 9881-0",
    email: "peershoop@therapiehilfe.de",
    web: "https://www.fachklinik-peers-hoop.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 26,
    gender: "gemischt",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Ehemaliger Bauernhof in Lindewitt OT Sillerup, Kreis Schleswig-Flensburg.",
    fokus: "Stationäre Langzeitentwöhnung vor allem bei Abhängigkeit von illegalen Drogen.",
    facts: ["Therapiehilfeverbund.", "Dörflich-naturnahe Lage.", "Handwerk und Tierpflege auf dem Gelände laut Trägerseite."],
  },
  {
    id: "ck-donnersberg",
    name: "Rehabilitationszentrum am Donnersberg",
    short: "Donnersberg",
    city: "Kirchheimbolanden",
    plz: "67292",
    street: "Dannenfelser Straße 42",
    st: "RP",
    traeger: "Evangelische Heimstiftung Pfalz",
    art: "kirche",
    phone: "06352 7536-0",
    email: "aufnahme-rzd@evh-pfalz.de",
    web: "https://www.evh-pfalz.de/",
    kind: "dual",
    glueck: true,
    subst: true,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "gemischt",
    setting: "beides",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Am Fuß des Donnersbergs am Rand von Kirchheimbolanden, Nordpfalz.",
    fokus: "Stationäre Entwöhnung inklusive Doppeldiagnose Psychose und Sucht sowie Adaption DomiZIEL.",
    facts: ["Evangelische Heimstiftung Pfalz.", "BtMG-Anerkennung.", "QReha-Liste zertifizierter Einrichtungen."],
  },
  {
    id: "ck-domiziel",
    name: "Adaptionshaus DomiZIEL",
    short: "DomiZIEL",
    city: "Kirchheimbolanden",
    plz: "67292",
    street: "Dannenfelser Straße 24a",
    st: "RP",
    traeger: "Evangelische Heimstiftung Pfalz",
    art: "kirche",
    phone: "06352 719495",
    email: "aufnahme-rzd@evh-pfalz.de",
    web: "https://www.evh-pfalz.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "adaption",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Rund zehn Gehminuten vom Rehabilitationszentrum am Donnersberg.",
    fokus: "Stationäre Adaption als zweite Phase nach Entwöhnung.",
    facts: ["Eigenes Adaptionshaus des RZD.", "Frauen, Männer und Paare ab 18.", "Nahtloser Übergang vom Donnersberg-Campus möglich."],
  },
  {
    id: "ck-magdalenenstift",
    name: "Suchtfachklinik Magdalenenstift",
    short: "Magdalenenstift",
    city: "Hartmannsdorf",
    plz: "09232",
    street: "Limbacher Straße 19b",
    st: "SN",
    traeger: "Stadtmission Chemnitz",
    art: "kirche",
    phone: "03722 40871-0",
    email: "magdalenenstift@stadtmission-chemnitz.de",
    web: "https://www.stadtmission-chemnitz.de/suchtfachklinik-magdalenenstift",
    kind: "sucht",
    alk: true,
    drog: false,
    med: true,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 16,
    gender: "maenner",
    setting: "stationaer",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Im Gebäude des Diakoniekrankenhauses Diakomed Hartmannsdorf.",
    fokus: "Stationäre medizinische Rehabilitation alkohol- und medikamentenabhängiger Männer.",
    facts: ["Stadtmission Chemnitz, seit 1990.", "Männerspezifisch.", "Eigene Werkstatt für Arbeitstherapie laut Trägerseite."],
  },
  {
    id: "ck-oelmuehle",
    name: "SRH Medinet Fachklinik Alte Ölmühle",
    short: "Alte Ölmühle",
    city: "Magdeburg",
    plz: "39114",
    street: "Berliner Chaussee 66",
    st: "ST",
    traeger: "SRH Medinet GmbH",
    art: "privat",
    phone: "0391 8104-0",
    email: "aufnahme-md@medinet-gmbh.de",
    web: "https://www.fachklinik-alte-oelmuehle.de/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 24,
    gender: "gemischt",
    setting: "beides",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: true,
    jung: false,
    room: "unbekannt",
    lage: "An der Berliner Chaussee in Magdeburg.",
    fokus: "Stationäre Entwöhnung, ganztägig ambulante Reha und Adaption; Schwerpunkt Medikamentenabhängigkeit.",
    facts: ["SRH Medinet, FVS-Mitglied.", "Schwerpunktklinik Medikamentenabhängigkeit der DRV Mitteldeutschland laut Trägerseite.", "Adaption in WG-Wohnungen."],
  },
  {
    id: "ck-blaukreuz-lippe",
    name: "Blaukreuz-Zentrum Lippe – Adaption",
    short: "Blaukreuz Adaption Lippe",
    city: "Bad Salzuflen",
    plz: "32105",
    street: "Am Steinbrink 44",
    st: "NW",
    traeger: "Blaues Kreuz Diakoniewerk",
    art: "kirche",
    phone: "05222 93986-0",
    web: "https://www.blaues-kreuz.de/de/westfalen/bad-salzuflen/adaption/information",
    kind: "sucht",
    alk: true,
    drog: false,
    med: true,
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "adaption",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Bad Salzuflen, Kreis Lippe.",
    fokus: "Zweite Phase der stationären medizinischen Rehabilitation nach Entwöhnung.",
    facts: ["Seit 1993 von der DRV Westfalen als Adaption anerkannt.", "NRW-BtMG-Liste Adaptionseinrichtungen.", "Nicht identisch mit Klinik Lipperland am Ort."],
  },
  {
    id: "ck-release-adaption",
    name: "Fachklinik Release – Adaption",
    short: "Release Adaption Hamm",
    city: "Hamm",
    plz: "59073",
    street: "Rosa-Luxemburg-Straße 41",
    st: "NW",
    traeger: "Netzwerk Suchthilfe gGmbH",
    art: "gemeinnuetzig",
    phone: "02381 68041",
    web: "https://www.therapieplaetze.de/einrichtungen/fachklinik-release-entwoehnung-adaption-und-nachsorge/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "adaption",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Hamm, eigener Adaptionsstandort getrennt von der Entwöhnungsklinik in Ascheberg.",
    fokus: "Stationäre und ganztägig ambulante Adaption nach Entwöhnung.",
    facts: ["Adaptionscampus zu Fachklinik Release Ascheberg.", "NRW-BtMG-anerkannte Adaptionseinrichtung.", "Anerkennung DRV Bund und Krankenkassen laut Verzeichnis."],
  },
  {
    id: "ck-tagesklinik-duesseldorf",
    name: "Tagesklinik für Suchtkranke Diakonie Düsseldorf",
    short: "Tagesklinik Diakonie Düsseldorf",
    city: "Düsseldorf",
    plz: "40233",
    street: "Langerstraße 2",
    st: "NW",
    traeger: "Diakonie Düsseldorf",
    art: "kirche",
    phone: "0211 7353264",
    email: "tagesklinik@diakonie-duesseldorf.de",
    web: "https://www.therapieplaetze.de/einrichtungen/tagesklinik-fuer-suchtkranke-diakonie-duesseldorf/",
    kind: "sucht",
    glueck: false,
    subst: true,
    substM: "Angabe liegt nicht vor",
    dmin: 12,
    dmax: 20,
    gender: "gemischt",
    setting: "tagesklinik",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: true,
    jung: false,
    room: "unbekannt",
    lage: "Düsseldorf-Flingern, Suchtberatungs- und Therapiezentrum Langerstraße.",
    fokus: "Ganztägig ambulante medizinische Rehabilitation bei Alkohol, Medikamenten und Drogen.",
    facts: ["Diakonie Düsseldorf, DeQus.", "NRW-Liste teilstationäre Entwöhnung.", "Nicht identisch mit der Schwarzbachklinik Ratingen."],
  },
  {
    id: "ck-adaption-bremen",
    name: "Externe Adaption Bremen",
    short: "Adaption Bremen",
    city: "Bremen",
    plz: "28195",
    street: "Am Wall 50-54",
    st: "HB",
    traeger: "Therapiehilfe Bremen gGmbH",
    art: "gemeinnuetzig",
    phone: "0421 2401110",
    web: "https://www.therapiehilfe.de/behandlung-stationaer/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "adaption",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Bremen-Mitte am Wall.",
    fokus: "Externe Adaption nach stationärer Entwöhnung.",
    facts: ["Therapiehilfeverbund.", "Getrennt vom RehaCentrum Alt-Osterholz.", "Städtische Adaption."],
  },
  {
    id: "ck-change-hamburg",
    name: "Tagesklinik CHANGE! Hamburg",
    short: "CHANGE! Hamburg",
    city: "Hamburg",
    plz: "22089",
    street: "Hasselbrookstraße 94a",
    st: "HH",
    traeger: "Therapiehilfe gGmbH",
    art: "gemeinnuetzig",
    phone: "040 2000102100",
    web: "https://www.therapiehilfe.de/behandlung-stationaer/",
    kind: "sucht",
    glueck: false,
    subst: false,
    substM: "Angabe liegt nicht vor",
    dmin: 8,
    dmax: 16,
    gender: "gemischt",
    setting: "tagesklinik",
    ahb: false,
    hv: true,
    kinder: false,
    trauma: false,
    jung: false,
    room: "unbekannt",
    lage: "Hamburg-Eilbek, Hasselbrookstraße, Therapiehilfe-Komplex.",
    fokus: "Ganztägig ambulante medizinische Rehabilitation für Suchtmittelabhängige.",
    facts: ["Therapiehilfeverbund.", "Tagesklinik, nicht Oldenfelder Tannen.", "BAR/deQus-Kontext der Trägergruppe."],
  }
];

export const HOUSES_WAVE3: HouseSpec[] = ROWS.map((item, index) => row(item, 251 + index));
