import type { GenderSetting, Indication, SettingKind } from "./types.ts";
import { HOUSES_EXTRA } from "./katalog-houses-extra.ts";

export type RoomKind =
  | "einbett"
  | "einbett-mehrheit"
  | "zweibett"
  | "zweibett-plus"
  | "kein-einbett"
  | "unbekannt";
export type WahlKind = "unbekannt";

const NA = "Angabe liegt nicht vor";

export type HouseSpec = {
  id: string;
  name: string;
  shortName: string;
  city: string;
  plz: string;
  street: string;
  stateCode: string;
  stateName: string;
  traeger: string;
  traegerArt: "drv" | "kirche" | "gemeinnuetzig" | "privat";
  phone: string;
  email: string;
  website: string;
  indicationAreas: Indication[];
  alkohol: boolean | null;
  drogen: boolean | null;
  medikamente: boolean | null;
  gluecksspiel: boolean;
  substitution: boolean;
  substMittel: string;
  substances: string[];
  therapyForms: string[];
  durationWeeksMin: number;
  durationWeeksMax: number;
  genderSetting: GenderSetting;
  setting: SettingKind;
  ahb: boolean;
  heilverfahren: boolean;
  barrierefrei: boolean;
  angehoerigenarbeit: boolean;
  kinderbetreuung: boolean;
  trauma: boolean;
  jungeErwachsene: boolean;
  placesEstimate: number;
  occupancyIndex: number;
  waitBaseDays: number;
  waitVarianceDays: number;
  sortOrder: number;
  speiseraum: boolean;
  besonderheit: "ruheraum" | "werkstatt" | "garten";
  room: RoomKind;
  wahl: WahlKind;
  lage: string;
  fokus: string;
  facts: string[];
};

const psycho = ["depression", "angst", "erschopfung"] as const;
const suchtAlkMed = ["alkohol", "medikamente"] as const;
const suchtAll = ["alkohol", "drogen", "medikamente"] as const;
const dualSub = ["alkohol", "drogen", "medikamente", "depression", "angst"] as const;
const einzelGruppe = ["Einzeltherapie", "Gruppentherapie", "Körpertherapie", "Sozialberatung"];

const HOUSES_CORE: HouseSpec[] = [
  {
    id: "ck-seewiesen",
    name: "Klinik Höhenried gGmbH",
    shortName: "Höhenried",
    city: "Bernried",
    plz: "82347",
    street: "Höhenried 1",
    stateCode: "BY",
    stateName: "Bayern",
    traeger: "Deutsche Rentenversicherung Bayern Süd",
    traegerArt: "drv",
    phone: "08158 24-0",
    email: "information@hoehenried.de",
    website: "https://www.hoehenried.de",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho, "schmerz"],
    therapyForms: [...einzelGruppe, "Kreativtherapie"],
    durationWeeksMin: 4,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: true,
    jungeErwachsene: false,
    placesEstimate: 150,
    occupancyIndex: 1.12,
    waitBaseDays: 32,
    waitVarianceDays: 10,
    sortOrder: 1,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Am Starnberger See, eigene Klinik der DRV Bayern Süd.",
    fokus: "Psychosomatische Rehabilitation in AHB und Heilverfahren, vorrangig Depression, Angst, Erschöpfung.",
    facts: [
      "DRV-eigene Klinik, keine private Trägerkette.",
      "Im selben Haus auch Kardiologie und Orthopädie — Psychosomatik ist eine Abteilung.",
      "See- und Parklage in Bernried, Anreise über Tutzing/Starnberg.",
    ],
  },
  {
    id: "ck-nordlicht",
    name: "Fachklinik Freudenholm-Ruhleben",
    shortName: "Freudenholm",
    city: "Schellhorn",
    plz: "24211",
    street: "Freudenholm 3",
    stateCode: "SH",
    stateName: "Schleswig-Holstein",
    traeger: "Landesverein für Innere Mission in Schleswig-Holstein",
    traegerArt: "kirche",
    phone: "04342 789 112",
    email: "fachklinik@landesverein.de",
    website: "https://landesverein.de/suchthilfe/fachklinik-freudenholm-ruhleben/",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: NA,
    substances: [...suchtAll],
    therapyForms: [...einzelGruppe, "Arbeitstherapie"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 90,
    occupancyIndex: 1.2,
    waitBaseDays: 48,
    waitVarianceDays: 14,
    sortOrder: 2,
    speiseraum: true,
    besonderheit: "werkstatt",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Zwei Standorte: Haus Freudenholm in Schellhorn und Haus Ruhleben in Bösdorf.",
    fokus: "Stationäre Entwöhnung bei Abhängigkeit von Alkohol, legalen und illegalen Drogen und Medikamenten.",
    facts: [
      "Diakonischer Träger (Landesverein für Innere Mission).",
      "Qualifizierter Entzug läuft nicht im Haus, sondern über das Psychiatrische Krankenhaus Rickling.",
      "Arbeitstherapie ist fester Bestandteil der Rehabilitation.",
    ],
  },
  {
    id: "ck-auwald",
    name: "MEDIAN Klinik Wilhelmsheim",
    shortName: "Wilhelmsheim",
    city: "Oppenweiler",
    plz: "71570",
    street: "Wilhelmsheim 1",
    stateCode: "BW",
    stateName: "Baden-Württemberg",
    traeger: "MEDIAN Kliniken",
    traegerArt: "privat",
    phone: "07193 52-0",
    email: "wilhelmsheim-kontakt@median-kliniken.de",
    website: "https://www.median-kliniken.de/de/klinik-wilhelmsheim/",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: false,
    medikamente: true,
    gluecksspiel: true,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...suchtAlkMed, "gluecksspiel"],
    therapyForms: [...einzelGruppe, "Indikativgruppen Glücksspiel"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 212,
    occupancyIndex: 1.18,
    waitBaseDays: 42,
    waitVarianceDays: 16,
    sortOrder: 3,
    speiseraum: true,
    besonderheit: "garten",
    room: "zweibett",
    wahl: "unbekannt",
    lage: "Waldlage bei Oppenweiler im Schwäbischen Wald, MEDIAN-Haus.",
    fokus: "Entwöhnung bei Alkohol- und Medikamentenabhängigkeit sowie pathologischem Glücksspiel.",
    facts: [
      "Rund 212 Behandlungsplätze, eines der größeren Suchthäuser in Baden-Württemberg.",
      "Illegale Drogen sind nicht der Aufnahmeauftrag.",
      "Eigene Glücksspielgruppen im Konzept.",
    ],
  },
  {
    id: "ck-weserblick",
    name: "MEDIAN Klinik am Park Bad Oeynhausen",
    shortName: "Klinik am Park",
    city: "Bad Oeynhausen",
    plz: "32545",
    street: "Westkorso 14",
    stateCode: "NW",
    stateName: "Nordrhein-Westfalen",
    traeger: "MEDIAN Kliniken",
    traegerArt: "privat",
    phone: "05731 865-2816",
    email: "kontakt.klinikampark@median-kliniken.de",
    website: "https://www.median-kliniken.de/de/klinik-am-park-bad-oeynhausen/",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe, "Physiotherapie"],
    durationWeeksMin: 4,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 175,
    occupancyIndex: 1.1,
    waitBaseDays: 28,
    waitVarianceDays: 8,
    sortOrder: 4,
    speiseraum: true,
    besonderheit: "ruheraum",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Innenstadtlage am Kurpark Bad Oeynhausen, unmittelbare Nachbarschaft zum historischen Wandelgang.",
    fokus: "Psychosomatische Rehabilitation inkl. AHB, stadtnahe Belastungserprobung möglich.",
    facts: [
      "Rund 175 Betten.",
      "Kurpark und Wandelhalle liegen fußläufig.",
      "Kein Sucht-Entwöhnungsauftrag.",
    ],
  },
  {
    id: "ck-bergstrasse",
    name: "Klinik Schloß Falkenhof",
    shortName: "Falkenhof",
    city: "Bensheim",
    plz: "64625",
    street: "Nibelungenstraße 109",
    stateCode: "HE",
    stateName: "Hessen",
    traeger: "Caritasverband Darmstadt e. V.",
    traegerArt: "kirche",
    phone: "06151 999-0",
    email: "c.helmes@caritas-darmstadt.de",
    website: "https://www.klinik-falkenhof.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: false,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...suchtAlkMed],
    therapyForms: [...einzelGruppe, "Arbeitstherapie"],
    durationWeeksMin: 13,
    durationWeeksMax: 16,
    genderSetting: "maenner",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 68,
    occupancyIndex: 1.15,
    waitBaseDays: 40,
    waitVarianceDays: 12,
    sortOrder: 5,
    speiseraum: true,
    besonderheit: "werkstatt",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Schlossanlage an der Bergstraße in Bensheim, Caritas Darmstadt.",
    fokus: "Männerspezifische Entwöhnung, seit 1968 als Männerhaus geführt.",
    facts: [
      "Nur Männer, 68 Plätze.",
      "Historisches Schloss plus moderner Anbau.",
      "Illegale Drogen sind nicht der Kernauftrag.",
    ],
  },
  {
    id: "ck-elbmarsch",
    name: "salus klinik Hürth – Fachklinik für Frauen",
    shortName: "salus Hürth",
    city: "Hürth",
    plz: "50354",
    street: "Argelés-sur-Mer-Straße 3",
    stateCode: "NW",
    stateName: "Nordrhein-Westfalen",
    traeger: "salus kliniken",
    traegerArt: "privat",
    phone: "02233 8081-0",
    email: "mail@salus-huerth.de",
    website: "https://www.salus-kliniken.de/huerth-frauen/",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: NA,
    substances: [...suchtAll, "trauma"],
    therapyForms: [...einzelGruppe, "Traumatherapie"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "frauen",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: true,
    trauma: true,
    jungeErwachsene: false,
    placesEstimate: 71,
    occupancyIndex: 1.22,
    waitBaseDays: 52,
    waitVarianceDays: 14,
    sortOrder: 6,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Frauenspezifisches Suchthaus in Hürth bei Köln, salus-Gruppe.",
    fokus: "Entwöhnung ausschließlich für Frauen, inkl. Mutter-Kind-Bereich.",
    facts: [
      "Nur Frauen. Mutter-Kind-Plätze nach Absprache.",
      "Traumafokus im Konzept ausgewiesen.",
      "Einbettzimmer als Regel.",
    ],
  },
  {
    id: "ck-rosenhoehe",
    name: "Reha-Zentrum Bad Mergentheim, Klinik Taubertal",
    shortName: "Klinik Taubertal",
    city: "Bad Mergentheim",
    plz: "97980",
    street: "Lothar-Götz-Straße 3",
    stateCode: "BW",
    stateName: "Baden-Württemberg",
    traeger: "Deutsche Rentenversicherung Bund",
    traegerArt: "drv",
    phone: "07931 591-0",
    email: "reha-klinik.taubertal@drv-bund.de",
    website: "https://www.reha-bad-mergentheim.de",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe, "Kreativtherapie"],
    durationWeeksMin: 4,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 120,
    occupancyIndex: 1.08,
    waitBaseDays: 30,
    waitVarianceDays: 11,
    sortOrder: 7,
    speiseraum: true,
    besonderheit: "ruheraum",
    room: "einbett",
    wahl: "unbekannt",
    lage: "DRV-Bund-Zentrum in Bad Mergentheim, Klinik Taubertal für Psychosomatik.",
    fokus: "Psychosomatische AHB und Heilverfahren im DRV-eigenen Reha-Zentrum.",
    facts: [
      "Träger ist die DRV Bund, kein privater Klinikkonzern.",
      "Mehrere Kliniken am Standort; Taubertal ist die psychosomatische.",
      "Kurstadt Bad Mergentheim, fußläufige Versorgung.",
    ],
  },
  {
    id: "ck-eifelhoehe",
    name: "MEDIAN Rehazentrum Daun – Thommener Höhe",
    shortName: "Thommener Höhe",
    city: "Darscheid",
    plz: "54552",
    street: "Thommener Höhe",
    stateCode: "RP",
    stateName: "Rheinland-Pfalz",
    traeger: "MEDIAN Kliniken",
    traegerArt: "privat",
    phone: "06592 201-0",
    email: "daun-kontakt@median-kliniken.de",
    website: "https://www.median-kliniken.de/de/rehazentrum-daun-thommener-hoehe/",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: false,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...suchtAlkMed],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 12,
    durationWeeksMax: 15,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 140,
    occupancyIndex: 1.16,
    waitBaseDays: 38,
    waitVarianceDays: 12,
    sortOrder: 8,
    speiseraum: false,
    besonderheit: "garten",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Eifelhöhe bei Daun/Darscheid, MEDIAN-Suchtklinik für Alkohol und Medikamente.",
    fokus: "Entwöhnung Alkohol und Medikamente in Höhenlage der Vulkaneifel.",
    facts: [
      "Illegale Drogen sind nicht der Aufnahmeauftrag.",
      "Teil des MEDIAN Rehazentrums Daun (mehrere Häuser am Ort).",
      "Hang- und Waldlage, Anreise über Daun.",
    ],
  },
  {
    id: "ck-lichtblick",
    name: "Asklepios Fachklinikum Wiesen",
    shortName: "Asklepios Wiesen",
    city: "Wildenfels",
    plz: "08134",
    street: "Parkstraße 10",
    stateCode: "SN",
    stateName: "Sachsen",
    traeger: "Asklepios",
    traegerArt: "privat",
    phone: "0341-4624320",
    email: "info.wiesen@asklepios.com",
    website: "https://www.asklepios.com/wiesen",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: NA,
    substances: [...suchtAll],
    therapyForms: [...einzelGruppe, "Arbeitstherapie"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 110,
    occupancyIndex: 1.14,
    waitBaseDays: 36,
    waitVarianceDays: 12,
    sortOrder: 9,
    speiseraum: true,
    besonderheit: "garten",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Parklage in Wiesen (Wildenfels), Westsachsen, Asklepios-Fachklinikum.",
    fokus: "Stationäre Entwöhnung bei Alkohol, Drogen und Medikamenten.",
    facts: [
      "Historischer Klinikstandort mit Park und Kapelle.",
      "Asklepios-Träger, GKV/DRV nach Kostenzusage.",
      "Keine ausgewiesene Glücksspielabteilung.",
    ],
  },
  {
    id: "ck-haffkueste",
    name: "MEDIAN Klinik Heiligendamm",
    shortName: "Heiligendamm",
    city: "Bad Doberan",
    plz: "18209",
    street: "Kinderstrand 1",
    stateCode: "MV",
    stateName: "Mecklenburg-Vorpommern",
    traeger: "MEDIAN Kliniken",
    traegerArt: "privat",
    phone: "0 38203 440",
    email: "info@median-kliniken.de",
    website: "https://www.median-kliniken.de/de/klinik-heiligendamm/",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe, "Klimatherapie"],
    durationWeeksMin: 4,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 160,
    occupancyIndex: 1.11,
    waitBaseDays: 34,
    waitVarianceDays: 10,
    sortOrder: 10,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett-mehrheit",
    wahl: "unbekannt",
    lage: "Direkt an der Ostsee in Heiligendamm, klassizistische Bäderarchitektur.",
    fokus: "Psychosomatische Reha inkl. AHB in Meereslage.",
    facts: [
      "Standort im ältesten deutschen Seebad.",
      "Eigene Seebrücke und Strandzugang am Klinikgelände.",
      "Kein Sucht-Entwöhnungsauftrag.",
    ],
  },
  {
    id: "ck-isargrund",
    name: "Fachklinik Weibersbrunn",
    shortName: "Weibersbrunn",
    city: "Weibersbrunn",
    plz: "63879",
    street: "Hauptstraße 36",
    stateCode: "BY",
    stateName: "Bayern",
    traeger: "Hephata Diakonie",
    traegerArt: "kirche",
    phone: "06094 9715-113",
    email: "elke.basser@hephata.de",
    website: "https://www.hephata.de/standort/fachklinik-weibersbrunn",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: false,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...suchtAlkMed],
    therapyForms: [...einzelGruppe, "Arbeitstherapie"],
    durationWeeksMin: 13,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 80,
    occupancyIndex: 1.17,
    waitBaseDays: 44,
    waitVarianceDays: 13,
    sortOrder: 11,
    speiseraum: true,
    besonderheit: "werkstatt",
    room: "einbett-mehrheit",
    wahl: "unbekannt",
    lage: "Spessart-Gemeinde Weibersbrunn zwischen Aschaffenburg und Würzburg.",
    fokus: "Entwöhnung bei Alkohol- und Medikamentenabhängigkeit.",
    facts: [
      "Waldlage im Hochspessart.",
      "Illegale Drogen nicht der Kernauftrag.",
      "Arbeitstherapie im Haus.",
    ],
  },
  {
    id: "ck-spreeaue",
    name: "MEDIAN Klinik Berlin-Kladow",
    shortName: "Berlin-Kladow",
    city: "Berlin",
    plz: "14089",
    street: "Kladower Damm 223",
    stateCode: "BE",
    stateName: "Berlin",
    traeger: "MEDIAN Kliniken",
    traegerArt: "privat",
    phone: "030 365030",
    email: "kontakt.berlin-kladow@median-kliniken.de",
    website: "https://www.median-kliniken.de/de/klinik-berlin-kladow/",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe, "Belastungserprobung Stadt"],
    durationWeeksMin: 4,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 200,
    occupancyIndex: 1.13,
    waitBaseDays: 26,
    waitVarianceDays: 8,
    sortOrder: 12,
    speiseraum: true,
    besonderheit: "garten",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Berlin-Kladow am Havelufer, stadtnahe psychosomatische Reha.",
    fokus: "Psychosomatik inkl. AHB mit Belastungserprobung in der Großstadt.",
    facts: [
      "Havel-Lage im Westen Berlins.",
      "Großes MEDIAN-Haus, städtische Anbindung per Bus/Fähre.",
      "Kein Sucht-Entwöhnungsauftrag.",
    ],
  },
  {
    id: "ck-teutoburg",
    name: "LWL-Klinikum Gütersloh, Bernhard-Salzmann-Klinik",
    shortName: "Bernhard-Salzmann",
    city: "Gütersloh",
    plz: "33334",
    street: "Hermann-Simon-Straße 7",
    stateCode: "NW",
    stateName: "Nordrhein-Westfalen",
    traeger: "Landschaftsverband Westfalen-Lippe",
    traegerArt: "gemeinnuetzig",
    phone: "05241 502-0",
    email: "info@lwl-klinik-guetersloh.de",
    website: "https://www.lwl-klinik-guetersloh.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: true,
    substitution: true,
    substMittel: NA,
    substances: [...suchtAll, "gluecksspiel", "substitution"],
    therapyForms: [...einzelGruppe, "Indikativgruppen nicht stoffgebunden"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 130,
    occupancyIndex: 1.19,
    waitBaseDays: 40,
    waitVarianceDays: 12,
    sortOrder: 13,
    speiseraum: true,
    besonderheit: "werkstatt",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "LWL-Gelände Gütersloh, öffentlich-rechtlicher Träger.",
    fokus: "Entwöhnung inkl. nicht stoffgebundener Sucht; Substitutionsmittel im Einzelfall nach Hausregel.",
    facts: [
      "Träger LWL, kein privater Konzern.",
      "Glücksspiel und andere nicht stoffgebundene Süchte sind ausgewiesen.",
      "Welches Substitutionsmittel konkret geführt wird: Angabe liegt nicht vor — Haus entscheidet.",
    ],
  },
  {
    id: "ck-mainbogen",
    name: "Fachklinik Haus Immanuel",
    shortName: "Haus Immanuel",
    city: "Thurnau",
    plz: "95349",
    street: "Am Schloßpark 6",
    stateCode: "BY",
    stateName: "Bayern",
    traeger: "Diakonie / Träger vor Ort",
    traegerArt: "kirche",
    phone: "09228-9968-0",
    email: "info-immanuel@dgd-stiftung.de",
    website: "https://www.haus-immanuel.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: false,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...suchtAlkMed],
    therapyForms: [...einzelGruppe, "Seelsorge"],
    durationWeeksMin: 13,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 70,
    occupancyIndex: 1.14,
    waitBaseDays: 42,
    waitVarianceDays: 12,
    sortOrder: 14,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Thurnau in Oberfranken, Schlossnähe, diakonisches Suchthaus.",
    fokus: "Entwöhnung Alkohol und Medikamente in einem kleineren diakonischen Haus.",
    facts: [
      "Christliches Hausprofil, Seelsorge im Angebot.",
      "Kleine Platzzahl, überschaubare Gruppen.",
      "Illegale Drogen nicht der Kernauftrag.",
    ],
  },
  {
    id: "ck-rothaar",
    name: "Klinik Brilon-Wald",
    shortName: "Brilon-Wald",
    city: "Brilon",
    plz: "59929",
    street: "Friedrich-Köster-Weg 2",
    stateCode: "NW",
    stateName: "Nordrhein-Westfalen",
    traeger: "Fuest Familienstiftung",
    traegerArt: "privat",
    phone: "02961 981-0",
    email: "info@reha-kbw.de",
    website: "https://www.reha-kbw.de",
    indicationAreas: ["dual"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: true,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...dualSub, "gluecksspiel", "trauma"],
    therapyForms: [...einzelGruppe, "Traumatherapie", "Eltern-Kind-Bereich"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: true,
    trauma: true,
    jungeErwachsene: false,
    placesEstimate: 130,
    occupancyIndex: 1.2,
    waitBaseDays: 46,
    waitVarianceDays: 14,
    sortOrder: 15,
    speiseraum: false,
    besonderheit: "garten",
    room: "einbett-mehrheit",
    wahl: "unbekannt",
    lage: "Sauerland, Hanglage in Brilon-Wald, barrierefrei ausgewiesen.",
    fokus: "Abhängigkeit von Alkohol, Drogen oder Medikamenten; Doppeldiagnosen und Traumafolgen mitbehandelt.",
    facts: [
      "130 Plätze, 100 Zimmer mit Dusche/WC, Sauna und Grillhütte.",
      "Eigener Bereich für Mütter oder Väter mit Kindern.",
      "Türkischsprachiges Angebot ausgewiesen. Barrierefrei inkl. Rollstuhl.",
    ],
  },
  {
    id: "ck-alsterufer",
    name: "Schön Klinik Hamburg Eilbek",
    shortName: "Eilbek",
    city: "Hamburg",
    plz: "22081",
    street: "Dehnhaide 120",
    stateCode: "HH",
    stateName: "Hamburg",
    traeger: "Schön Klinik",
    traegerArt: "privat",
    phone: "040 2092-0",
    email: NA,
    website: "https://www.schoen-klinik.de/hamburg-eilbek",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe, "AHB", "Physio"],
    durationWeeksMin: 3,
    durationWeeksMax: 5,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 80,
    occupancyIndex: 1.17,
    waitBaseDays: 30,
    waitVarianceDays: 9,
    sortOrder: 16,
    speiseraum: true,
    besonderheit: "ruheraum",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Hamburg-Eilbek, städtisches Akut- und Rehahaus der Schön Klinik.",
    fokus: "Psychosomatik in einem innerstädtischen Haus mit AHB-Option.",
    facts: [
      "Kein Sucht-Entwöhnungsauftrag.",
      "Stadtnahe Belastungserprobung in Hamburg möglich.",
      "Mehrere Fachabteilungen am Standort, Psychosomatik ist eine davon.",
    ],
  },
  {
    id: "ck-eusserthal",
    name: "Fachklinik Eußerthal",
    shortName: "Eußerthal",
    city: "Eußerthal",
    plz: "76857",
    street: "Klinikstraße 1",
    stateCode: "RP",
    stateName: "Rheinland-Pfalz",
    traeger: "Deutsche Rentenversicherung Rheinland-Pfalz",
    traegerArt: "drv",
    phone: "06345 20-0",
    email: "fachklinik-eusserthal@drv-rlp.de",
    website: "https://www.fachklinik-eusserthal.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...suchtAll],
    therapyForms: [...einzelGruppe, "Arbeitstherapie"],
    durationWeeksMin: 13,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 180,
    occupancyIndex: 1.15,
    waitBaseDays: 40,
    waitVarianceDays: 12,
    sortOrder: 17,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Pfälzerwald, DRV-eigene Fachklinik in Klosterlage.",
    fokus: "Entwöhnung Alkohol, Drogen und Medikamente in DRV-Regie.",
    facts: [
      "DRV Rheinland-Pfalz ist Träger, keine private Kette.",
      "Einbettzimmer als Regel.",
      "Historischer Klosterbau plus moderne Anbauten im Wald.",
    ],
  },
  {
    id: "ck-muenchwies",
    name: "MEDIAN Klinik Münchwies",
    shortName: "Münchwies",
    city: "Neunkirchen",
    plz: "66540",
    street: "Kurhausstraße 30",
    stateCode: "SL",
    stateName: "Saarland",
    traeger: "MEDIAN Kliniken",
    traegerArt: "privat",
    phone: "06858 691-0",
    email: "muenchwies-kontakt@median-kliniken.de",
    website: "https://www.median-kliniken.de/de/klinik-muenchwies/",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: NA,
    substances: [...suchtAll],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 150,
    occupancyIndex: 1.16,
    waitBaseDays: 38,
    waitVarianceDays: 12,
    sortOrder: 18,
    speiseraum: true,
    besonderheit: "garten",
    room: "zweibett",
    wahl: "unbekannt",
    lage: "Höhenlage über Neunkirchen, Saarland, MEDIAN-Suchtklinik.",
    fokus: "Entwöhnung bei stoffgebundenen Abhängigkeiten.",
    facts: [
      "Weitblick über das Saarland von den Stationen.",
      "Mehrere Gebäude auf dem Klinikberg.",
      "Substitutionsmittel: Angabe liegt nicht vor.",
    ],
  },
  {
    id: "ck-berus",
    name: "MEDIAN Klinik Berus",
    shortName: "Berus",
    city: "Überherrn",
    plz: "66802",
    street: "Orannastraße 55",
    stateCode: "SL",
    stateName: "Saarland",
    traeger: "MEDIAN Kliniken",
    traegerArt: "privat",
    phone: "06836 39-0",
    email: "berus-kontakt@median-kliniken.de",
    website: "https://www.median-kliniken.de/de/klinik-berus/",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 4,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 140,
    occupancyIndex: 1.1,
    waitBaseDays: 32,
    waitVarianceDays: 10,
    sortOrder: 19,
    speiseraum: true,
    besonderheit: "ruheraum",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Berus/Überherrn an der französisch-saarländischen Grenze.",
    fokus: "Psychosomatische Rehabilitation inkl. AHB.",
    facts: [
      "Grenznahe Lage, Anreise auch aus Lothringen üblich.",
      "Kein Sucht-Entwöhnungsauftrag.",
      "MEDIAN-Haus mit Parkgelände.",
    ],
  },
  {
    id: "ck-roseneck",
    name: "Schön Klinik Roseneck",
    shortName: "Roseneck",
    city: "Prien am Chiemsee",
    plz: "83209",
    street: "Am Roseneck 6",
    stateCode: "BY",
    stateName: "Bayern",
    traeger: "Schön Klinik",
    traegerArt: "privat",
    phone: "08051 68-100299",
    email: NA,
    website: "https://www.schoen-klinik.de/roseneck",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho, "ess"],
    therapyForms: [...einzelGruppe, "Essstörungskonzept"],
    durationWeeksMin: 8,
    durationWeeksMax: 12,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: true,
    jungeErwachsene: true,
    placesEstimate: 300,
    occupancyIndex: 1.25,
    waitBaseDays: 55,
    waitVarianceDays: 16,
    sortOrder: 20,
    speiseraum: true,
    besonderheit: "garten",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Prien am Chiemsee, Stammhaus der Schön Klinik für Psychosomatik und Essstörungen.",
    fokus: "Psychosomatik mit ausgewiesenem Schwerpunkt Essstörungen.",
    facts: [
      "Eines der größten psychosomatischen Häuser in Deutschland.",
      "Chiemsee-Lage, mehrere Klinikgebäude im Ort.",
      "Kein Sucht-Entwöhnungsauftrag.",
    ],
  },
  {
    id: "ck-heiligenfeld",
    name: "Fachklinik Heiligenfeld Bad Kissingen",
    shortName: "Heiligenfeld",
    city: "Bad Kissingen",
    plz: "97688",
    street: "Altenbergweg 6",
    stateCode: "BY",
    stateName: "Bayern",
    traeger: "Heiligenfeld Kliniken",
    traegerArt: "privat",
    phone: "0971 84-4195",
    email: "info@heiligenfeld.de",
    website: "https://www.heiligenfeld.de/kliniken/fachklinik-heiligenfeld-bad-kissingen",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho, "trauma"],
    therapyForms: [...einzelGruppe, "Körpertherapie"],
    durationWeeksMin: 6,
    durationWeeksMax: 10,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: true,
    jungeErwachsene: false,
    placesEstimate: 180,
    occupancyIndex: 1.18,
    waitBaseDays: 48,
    waitVarianceDays: 14,
    sortOrder: 21,
    speiseraum: true,
    besonderheit: "garten",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Hanglage über Bad Kissingen, Parkgelände der Heiligenfeld-Gruppe.",
    fokus: "Psychosomatische Heilverfahren, Traumafokus nach interner Einschätzung.",
    facts: [
      "Mehrere Heiligenfeld-Häuser in Kissingen; dies ist die Fachklinik, nicht die Rosengartenklinik.",
      "Park- und Hanglage, Kurstadt.",
      "Kein Sucht-Entwöhnungsauftrag.",
    ],
  },
  {
    id: "ck-glotterbad",
    name: "Rehaklinik Glotterbad",
    shortName: "Glotterbad",
    city: "Glottertal",
    plz: "79286",
    street: "Wirthstraße 11",
    stateCode: "BW",
    stateName: "Baden-Württemberg",
    traeger: "Rehaklinik Glotterbad / Träger vor Ort",
    traegerArt: "gemeinnuetzig",
    phone: "07684 809-0",
    email: "info@rehaklinik-glotterbad.de",
    website: "https://www.rehaklinik-glotterbad.de",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 5,
    durationWeeksMax: 8,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 100,
    occupancyIndex: 1.12,
    waitBaseDays: 36,
    waitVarianceDays: 11,
    sortOrder: 22,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Glottertal im Schwarzwald, historisches Kurhaus mit Holzsteg.",
    fokus: "Psychosomatische Rehabilitation in Schwarzwaldlage.",
    facts: [
      "Historischer Bäderstandort, umgebaut zur Rehaklinik.",
      "Steile Hanglage, Barrierefreiheit eingeschränkt.",
      "Kein Sucht-Entwöhnungsauftrag.",
    ],
  },
  {
    id: "ck-landelin",
    name: "AGJ-Fachklinik St. Landelin",
    shortName: "St. Landelin",
    city: "Herbolzheim",
    plz: "79336",
    street: "Riedstraße 15",
    stateCode: "BW",
    stateName: "Baden-Württemberg",
    traeger: "AGJ-Fachverband / Caritas Freiburg",
    traegerArt: "kirche",
    phone: "07643 9161-0",
    email: "st.landelin@agj-freiburg.de",
    website: "https://agj-fachklinik-st-landelin.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: false,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: ["alkohol", "cannabis"],
    therapyForms: [...einzelGruppe, "Seelsorge", "Therapeutisches Klettern"],
    durationWeeksMin: 13,
    durationWeeksMax: 16,
    genderSetting: "maenner",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 60,
    occupancyIndex: 1.15,
    waitBaseDays: 42,
    waitVarianceDays: 12,
    sortOrder: 23,
    speiseraum: true,
    besonderheit: "werkstatt",
    room: "zweibett",
    wahl: "unbekannt",
    lage: "Herbolzheim im Breisgau, AGJ-Fachklinik, kirchlicher Träger.",
    fokus: "Männerspezifische Entwöhnung, Schwerpunkt Alkohol- und/oder Cannabisabhängigkeit.",
    facts: [
      "Nur Männer, rund 60 Plätze. 18 Einzel- und 24 Doppelzimmer mit Dusche/WC.",
      "Seit 1970. Träger: AGJ-Fachverband für Prävention und Rehabilitation, Erzdiözese Freiburg.",
      "Therapeutisches Klettern, Sauna, Grillplatz und Barfußpfad sind ausgewiesen.",
      "Illegale Drogen außer Cannabis sind nicht der Kernauftrag; Mehrfachabhängigkeit nur nach Vorgespräch.",
    ],
  },
  {
    id: "ck-furth",
    name: "Johannesbad Fachklinik Furth im Wald",
    shortName: "Furth im Wald",
    city: "Furth im Wald",
    plz: "93437",
    street: "Sommerau 1",
    stateCode: "BY",
    stateName: "Bayern",
    traeger: "Johannesbad Gruppe",
    traegerArt: "privat",
    phone: "09973 502-0",
    email: "info.furth@johannesbad.com",
    website: "https://www.johannesbad.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: NA,
    substances: [...suchtAll],
    therapyForms: [...einzelGruppe, "Arbeitstherapie"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 90,
    occupancyIndex: 1.16,
    waitBaseDays: 40,
    waitVarianceDays: 12,
    sortOrder: 24,
    speiseraum: true,
    besonderheit: "garten",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Bayerischer Wald, Grenzlage zu Tschechien.",
    fokus: "Entwöhnung bei stoffgebundenen Abhängigkeiten, Johannesbad-Gruppe.",
    facts: [
      "Waldlage Sommerau, ruhiger Standort.",
      "Johannesbad betreibt mehrere Fachkliniken; dies ist der Furth-Standort.",
      "Substitutionsmittel: Angabe liegt nicht vor.",
    ],
  },
  {
    id: "ck-seehof",
    name: "Reha-Zentrum Seehof",
    shortName: "Seehof",
    city: "Teltow",
    plz: "14513",
    street: "Lichterfelder Allee 55",
    stateCode: "BB",
    stateName: "Brandenburg",
    traeger: "Deutsche Rentenversicherung Bund",
    traegerArt: "drv",
    phone: "03328 345-0",
    email: "reha-klinik.seehof@drv-bund.de",
    website: "https://www.reha-klinik-seehof.de",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 4,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 200,
    occupancyIndex: 1.09,
    waitBaseDays: 28,
    waitVarianceDays: 8,
    sortOrder: 25,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Teltow südlich von Berlin, DRV-Bund-eigenes Reha-Zentrum.",
    fokus: "Psychosomatische AHB und Heilverfahren, stadtnahe Lage zu Berlin.",
    facts: [
      "DRV Bund ist Träger.",
      "S-Bahn-Nähe Berlin macht Belastungserprobung in der Hauptstadt möglich.",
      "Kein Sucht-Entwöhnungsauftrag.",
    ],
  },
  {
    id: "ck-tannenhof",
    name: "Tannenhof Berlin-Brandenburg",
    shortName: "Tannenhof",
    city: "Birkenwerder",
    plz: "16547",
    street: "Summter Straße 16",
    stateCode: "BB",
    stateName: "Brandenburg",
    traeger: "Tannenhof Berlin-Brandenburg e. V.",
    traegerArt: "gemeinnuetzig",
    phone: "030 864946-0",
    email: "zentrale@tannenhof.de",
    website: "https://www.tannenhof.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: true,
    substMittel: NA,
    substances: [...suchtAll, "substitution"],
    therapyForms: [...einzelGruppe, "Adaption"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 80,
    occupancyIndex: 1.2,
    waitBaseDays: 44,
    waitVarianceDays: 14,
    sortOrder: 26,
    speiseraum: true,
    besonderheit: "werkstatt",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Birkenwerder nördlich von Berlin, gemeinnütziger Suchthilfeträger.",
    fokus: "Entwöhnung inkl. illegaler Drogen; Substitution im Einzelfall nach Hausregel.",
    facts: [
      "Träger ist ein Verein, kein Klinikkonzern.",
      "Auch Adaptionsplätze im Verbund.",
      "Welches Substitutionsmittel geführt wird: Angabe liegt nicht vor.",
    ],
  },
  {
    id: "ck-oldenfelde",
    name: "Therapiehilfe Fachklinik Oldenfelder Tannen",
    shortName: "Oldenfelder Tannen",
    city: "Hamburg",
    plz: "22143",
    street: "Am Stadtrand 70",
    stateCode: "HH",
    stateName: "Hamburg",
    traeger: "Therapiehilfe e. V.",
    traegerArt: "gemeinnuetzig",
    phone: "040 200010 1200 /",
    email: NA,
    website: "https://www.therapiehilfe.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: true,
    substMittel: NA,
    substances: [...suchtAll, "substitution"],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 60,
    occupancyIndex: 1.18,
    waitBaseDays: 40,
    waitVarianceDays: 12,
    sortOrder: 27,
    speiseraum: false,
    besonderheit: "werkstatt",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Hamburg-Rahlstedt, städtisches Suchthaus der Therapiehilfe.",
    fokus: "Entwöhnung inkl. Drogen in Hamburg; Substitution nach Hausregel.",
    facts: [
      "Gemeinnütziger Hamburger Träger.",
      "Stadtnahe Lage, Belastungserprobung im Alltag möglich.",
      "Substitutionsmittel: Angabe liegt nicht vor.",
    ],
  },
  {
    id: "ck-borkum",
    name: "Klinik Borkum Riff",
    shortName: "Borkum Riff",
    city: "Borkum",
    plz: "26757",
    street: "Hindenburgstraße 6",
    stateCode: "NI",
    stateName: "Niedersachsen",
    traeger: "Deutsche Rentenversicherung Rheinland",
    traegerArt: "drv",
    phone: "04922 302 - 0",
    email: "reha-klinik.borkumriff@drv-bund.de",
    website: "https://www.reha-klinik-borkum-riff.de",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe, "Klimatherapie"],
    durationWeeksMin: 3,
    durationWeeksMax: 5,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: false,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 170,
    occupancyIndex: 1.08,
    waitBaseDays: 24,
    waitVarianceDays: 8,
    sortOrder: 28,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Nordseeinsel Borkum, DRV-Rehazentrum mit psychosomatischer Abteilung.",
    fokus: "Psychosomatische Reha in Insel- und Reizklima.",
    facts: [
      "Anreise nur per Fähre, das verlängert An- und Abreise.",
      "DRV-eigenes Haus, mehrere Indikationen am Standort.",
      "Kein Sucht-Entwöhnungsauftrag.",
    ],
  },
  {
    id: "ck-erlengrund",
    name: "Fachklinik Erlengrund",
    shortName: "Erlengrund",
    city: "Salzgitter",
    plz: "38259",
    street: "Erlengrund 1",
    stateCode: "NI",
    stateName: "Niedersachsen",
    traeger: "Träger vor Ort",
    traegerArt: "gemeinnuetzig",
    phone: "05331 8852 0",
    email: "info@lukas-werk.de",
    website: "https://www.fachklinik-erlengrund.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: false,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...suchtAlkMed],
    therapyForms: [...einzelGruppe, "Arbeitstherapie"],
    durationWeeksMin: 13,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 70,
    occupancyIndex: 1.14,
    waitBaseDays: 38,
    waitVarianceDays: 12,
    sortOrder: 29,
    speiseraum: true,
    besonderheit: "werkstatt",
    room: "einbett-mehrheit",
    wahl: "unbekannt",
    lage: "Salzgitter, niedersächsisches Suchthaus für Alkohol und Medikamente.",
    fokus: "Entwöhnung Alkohol und Medikamente.",
    facts: [
      "Kleinere Klinik, überschaubare Gruppen.",
      "Illegale Drogen nicht der Kernauftrag.",
      "Arbeitstherapie im Konzept.",
    ],
  },
  {
    id: "ck-waldschloesschen",
    name: "Therapiezentrum OPEN",
    shortName: "OPEN Göttingen",
    city: "Göttingen",
    plz: "37075",
    street: "Waldschlösschenweg",
    stateCode: "NI",
    stateName: "Niedersachsen",
    traeger: "Deutscher Orden / Ordenswerke",
    traegerArt: "kirche",
    phone: "0551 900498-0",
    email: "open.aufnahme@deutscher-orden.de",
    website: "https://www.goettingen-suchthilfe.de",
    indicationAreas: ["dual"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: NA,
    substances: [...dualSub],
    therapyForms: [...einzelGruppe, "Arbeitstherapie", "Adaption"],
    durationWeeksMin: 12,
    durationWeeksMax: 22,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: true,
    jungeErwachsene: false,
    placesEstimate: 45,
    occupancyIndex: 1.21,
    waitBaseDays: 50,
    waitVarianceDays: 14,
    sortOrder: 30,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett-mehrheit",
    wahl: "unbekannt",
    lage: "Göttingen, umgebautes Fabrikgebäude mit Parkgelände, Deutscher Orden.",
    fokus: "Stationäre Entwöhnung inkl. illegaler Drogen; Dualdiagnose und Adaption im Haus.",
    facts: [
      "45 Plätze: 20 stationär Männer, 14 stationär Frauen im eigenen Bereich, 11 Adaption.",
      "Richtwert bis 22 Wochen bei Abhängigkeit von illegalen Drogen; Adaption schließt an.",
      "Ein- und Zweibettzimmer mit eigenem Bad. Ein rollstuhlgerechter Platz ist ausgewiesen.",
      "Fitnessraum, Werkstätten, Sauna und Beachvolleyball auf dem Gelände.",
    ],
  },
  {
    id: "ck-sonnenberg",
    name: "MEDIAN Reha-Zentrum Wiesbaden Sonnenberg",
    shortName: "Sonnenberg",
    city: "Wiesbaden",
    plz: "65191",
    street: "Rheingaustraße 84",
    stateCode: "HE",
    stateName: "Hessen",
    traeger: "MEDIAN Kliniken",
    traegerArt: "privat",
    phone: "0611 571-0",
    email: "kontakt.sonnenberg@median-kliniken.de",
    website: "https://www.median-kliniken.de/de/reha-zentrum-wiesbaden-sonnenberg/",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 4,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 160,
    occupancyIndex: 1.11,
    waitBaseDays: 30,
    waitVarianceDays: 9,
    sortOrder: 31,
    speiseraum: true,
    besonderheit: "ruheraum",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Wiesbaden-Sonnenberg, stadtnahe psychosomatische Reha.",
    fokus: "Psychosomatik inkl. AHB, Belastungserprobung in der Landeshauptstadt möglich.",
    facts: [
      "Kein Sucht-Entwöhnungsauftrag.",
      "MEDIAN-Haus mit mehreren Fachabteilungen am Reha-Zentrum.",
      "Gute ÖPNV-Anbindung Wiesbaden.",
    ],
  },
  {
    id: "ck-nauheim",
    name: "salus kliniken Bad Nauheim",
    shortName: "salus Bad Nauheim",
    city: "Bad Nauheim",
    plz: "61231",
    street: "Lichtengraben 17",
    stateCode: "HE",
    stateName: "Hessen",
    traeger: "salus kliniken",
    traegerArt: "privat",
    phone: "06032 9917-0",
    email: "s.igelmund@salus-kliniken.de",
    website: "https://www.salus-kliniken.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: NA,
    substances: [...suchtAll],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 120,
    occupancyIndex: 1.17,
    waitBaseDays: 42,
    waitVarianceDays: 12,
    sortOrder: 32,
    speiseraum: true,
    besonderheit: "garten",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Kurstadt Bad Nauheim, salus-Suchtklinik.",
    fokus: "Entwöhnung bei stoffgebundenen Abhängigkeiten.",
    facts: [
      "salus betreibt mehrere Suchthäuser; Hürth bleibt das Frauenhaus, Nauheim ist gemischt.",
      "Kurstadt-Infrastruktur fußläufig.",
      "Substitutionsmittel: Angabe liegt nicht vor.",
    ],
  },
  {
    id: "ck-richelsdorf",
    name: "MEDIAN Klinik Richelsdorf",
    shortName: "Richelsdorf",
    city: "Wildeck",
    plz: "36208",
    street: "Schlossstraße",
    stateCode: "HE",
    stateName: "Hessen",
    traeger: "MEDIAN Kliniken",
    traegerArt: "privat",
    phone: "06626 9222-0",
    email: "richelsdorf-kontakt@median-kliniken.de",
    website: "https://www.median-kliniken.de/de/klinik-richelsdorf/",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: NA,
    substances: [...suchtAll],
    therapyForms: [...einzelGruppe, "Arbeitstherapie"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 100,
    occupancyIndex: 1.16,
    waitBaseDays: 40,
    waitVarianceDays: 12,
    sortOrder: 33,
    speiseraum: true,
    besonderheit: "werkstatt",
    room: "zweibett",
    wahl: "unbekannt",
    lage: "Richelsdorf (Wildeck) in Osthessen, Schloss- und Waldlage.",
    fokus: "Entwöhnung bei stoffgebundenen Abhängigkeiten.",
    facts: [
      "Abgelegene Lage, wenig städtische Reize.",
      "MEDIAN-Haus.",
      "Substitutionsmittel: Angabe liegt nicht vor.",
    ],
  },
  {
    id: "ck-waren",
    name: "AHG Klinik Waren",
    shortName: "AHG Waren",
    city: "Waren (Müritz)",
    plz: "17192",
    street: "Nygrener Straße 8",
    stateCode: "MV",
    stateName: "Mecklenburg-Vorpommern",
    traeger: "AHG / MEDIAN",
    traegerArt: "privat",
    phone: "03991 635-0",
    email: "waren-kontakt@median-kliniken.de",
    website: "https://www.ahg.de",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 5,
    durationWeeksMax: 7,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 140,
    occupancyIndex: 1.1,
    waitBaseDays: 32,
    waitVarianceDays: 10,
    sortOrder: 34,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Waren an der Müritz, Seenplatte.",
    fokus: "Psychosomatische Rehabilitation in Seelage.",
    facts: [
      "Müritz-Lage, Rad- und Wanderwege unmittelbar.",
      "Kein Sucht-Entwöhnungsauftrag.",
      "AHG-Standort, heute MEDIAN-Gruppe.",
    ],
  },
  {
    id: "ck-driburg",
    name: "AHG Klinik Bad Driburg",
    shortName: "AHG Bad Driburg",
    city: "Bad Driburg",
    plz: "33014",
    street: "Kaiserallee 3",
    stateCode: "NW",
    stateName: "Nordrhein-Westfalen",
    traeger: "AHG / MEDIAN",
    traegerArt: "privat",
    phone: NA,
    email: NA,
    website: "https://www.ahg.de",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho, "trauma"],
    therapyForms: [...einzelGruppe, "Traumatherapie"],
    durationWeeksMin: 5,
    durationWeeksMax: 8,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: true,
    jungeErwachsene: false,
    placesEstimate: 150,
    occupancyIndex: 1.14,
    waitBaseDays: 36,
    waitVarianceDays: 11,
    sortOrder: 35,
    speiseraum: true,
    besonderheit: "ruheraum",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Kurstadt Bad Driburg, Teutoburger Wald.",
    fokus: "Psychosomatik inkl. Traumafokus nach interner Einschätzung.",
    facts: [
      "Kurpark und Gradierwerk fußläufig.",
      "Kein Sucht-Entwöhnungsauftrag.",
      "AHG-Standort.",
    ],
  },
  {
    id: "ck-holthausen",
    name: "Johannesbad Fachklinik Holthausen",
    shortName: "Holthausen",
    city: "Hattingen",
    plz: "45527",
    street: "Holthausen",
    stateCode: "NW",
    stateName: "Nordrhein-Westfalen",
    traeger: "Johannesbad Gruppe",
    traegerArt: "privat",
    phone: "02974 778-0",
    email: "info.hm@johannesbad.com",
    website: "https://www.johannesbad.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: NA,
    substances: [...suchtAll],
    therapyForms: [...einzelGruppe, "Arbeitstherapie"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 100,
    occupancyIndex: 1.17,
    waitBaseDays: 42,
    waitVarianceDays: 12,
    sortOrder: 36,
    speiseraum: true,
    besonderheit: "werkstatt",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Hattingen-Holthausen an der Ruhr, Johannesbad-Suchtklinik.",
    fokus: "Entwöhnung bei stoffgebundenen Abhängigkeiten.",
    facts: [
      "Ruhrgebietslage, stadtnahe Belastungserprobung möglich.",
      "Johannesbad-Gruppe.",
      "Substitutionsmittel: Angabe liegt nicht vor.",
    ],
  },
  {
    id: "ck-ratingen",
    name: "Schwarzbachklinik Ratingen",
    shortName: "Schwarzbach",
    city: "Ratingen",
    plz: "40880",
    street: "Niederbeckweg 6",
    stateCode: "NW",
    stateName: "Nordrhein-Westfalen",
    traeger: "Deutscher Orden / Ordenswerke",
    traegerArt: "kirche",
    phone: "02102 443300",
    email: "ordenswerke@deutscher-orden.de",
    website: "https://www.suchthilfe-duesseldorf.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: true,
    substitution: true,
    substMittel: "Methadon oder Buprenorphin, nach Hausregel",
    substances: [...suchtAll, "gluecksspiel", "substitution"],
    therapyForms: [...einzelGruppe, "Arbeitstherapie"],
    durationWeeksMin: 16,
    durationWeeksMax: 26,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 56,
    occupancyIndex: 1.22,
    waitBaseDays: 48,
    waitVarianceDays: 14,
    sortOrder: 37,
    speiseraum: true,
    besonderheit: "werkstatt",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Ratingen bei Düsseldorf, denkmalgeschützte Villa plus Neubau, Deutscher Orden.",
    fokus: "Entwöhnung inkl. illegaler Drogen; Substitution mit Methadon oder Buprenorphin nach Hausregel.",
    facts: [
      "56 vollstationäre Plätze, Schwerpunkt illegale Drogen (auch kombiniert mit Alkohol/Medikamenten).",
      "Paarbehandlung ist ausgewiesen. Dualdiagnose (psychiatrische Begleiterkrankung) ist Schwerpunkt.",
      "Regeldauer bis 26 Wochen. Anbindung Düsseldorf per U72 (Felderhof).",
      "Welches Substitutionsmittel im Einzelfall: Haus entscheidet, nicht Lohklar.",
    ],
  },
  {
    id: "ck-fredeburg",
    name: "Johannesbad Fachklinik Bad Fredeburg",
    shortName: "Bad Fredeburg",
    city: "Schmallenberg",
    plz: "57392",
    street: "Auf der Schmitt 1",
    stateCode: "NW",
    stateName: "Nordrhein-Westfalen",
    traeger: "Johannesbad Gruppe",
    traegerArt: "privat",
    phone: "02974 73-0",
    email: "info.hsl@johannesbad.com",
    website: "https://www.johannesbad.de",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 5,
    durationWeeksMax: 7,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 120,
    occupancyIndex: 1.12,
    waitBaseDays: 34,
    waitVarianceDays: 10,
    sortOrder: 38,
    speiseraum: true,
    besonderheit: "garten",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Bad Fredeburg im Sauerland, Johannesbad-Psychosomatik.",
    fokus: "Psychosomatische Rehabilitation in Mittelgebirgslage.",
    facts: [
      "Kein Sucht-Entwöhnungsauftrag (im Gegensatz zu Holthausen/Furth derselben Gruppe).",
      "Kurort Schmallenberg-Fredeburg.",
      "Wanderwege unmittelbar.",
    ],
  },
  {
    id: "ck-bergzabern",
    name: "Celenus Parkklinik Bad Bergzabern",
    shortName: "Parkklinik Bergzabern",
    city: "Bad Bergzabern",
    plz: "76887",
    street: "Kurtalstraße 83-85",
    stateCode: "RP",
    stateName: "Rheinland-Pfalz",
    traeger: "emeis / Celenus Kliniken",
    traegerArt: "privat",
    phone: "06343 942-0",
    email: "info@parkklinik-bad-bergzabern.de",
    website: "https://www.celenus-kliniken.de/bad-bergzabern/",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 4,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 110,
    occupancyIndex: 1.1,
    waitBaseDays: 30,
    waitVarianceDays: 9,
    sortOrder: 39,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Südpfalz, Kurort Bad Bergzabern an der Weinstraße, wenige Kilometer zum Elsass.",
    fokus: "Psychosomatische AHB und Heilverfahren, inkl. Tinnitus und Hyperakusis.",
    facts: [
      "137 Einzelzimmer (stationär) — Einbett als Regel, kein Mehrbett.",
      "Schwerpunkte u. a. Depression, Angst, Tinnitus, Hyperakusis, PTBS.",
      "Marke Celenus tritt als emeis auf; Träger bleibt die Klinikengruppe.",
    ],
  },
  {
    id: "ck-thonberg",
    name: "Fachklinik Thonberg",
    shortName: "Thonberg",
    city: "Leipzig",
    plz: "04319",
    street: "Thonberg",
    stateCode: "SN",
    stateName: "Sachsen",
    traeger: "Träger vor Ort",
    traegerArt: "gemeinnuetzig",
    phone: NA,
    email: NA,
    website: "https://www.fachklinik-thonberg.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: true,
    substMittel: NA,
    substances: [...suchtAll, "substitution"],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 90,
    occupancyIndex: 1.18,
    waitBaseDays: 40,
    waitVarianceDays: 12,
    sortOrder: 40,
    speiseraum: true,
    besonderheit: "werkstatt",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Leipzig-Thonberg, städtisches Suchthaus.",
    fokus: "Entwöhnung inkl. Drogen in Leipzig; Substitution nach Hausregel.",
    facts: [
      "Stadtnahe Lage, Alltagserprobung in Leipzig möglich.",
      "Substitutionsmittel: Angabe liegt nicht vor.",
      "Gemeinnütziger Träger.",
    ],
  },
  {
    id: "ck-elbingerode",
    name: "Fachklinik Elbingerode",
    shortName: "Elbingerode",
    city: "Oberharz am Brocken",
    plz: "38875",
    street: "Krankenhausweg",
    stateCode: "ST",
    stateName: "Sachsen-Anhalt",
    traeger: "Diakonie",
    traegerArt: "kirche",
    phone: "039454 8-2701",
    email: "reha.sekretariat@diako-harz.de",
    website: "https://www.fachklinik-elbingerode.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: false,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...suchtAlkMed],
    therapyForms: [...einzelGruppe, "Seelsorge"],
    durationWeeksMin: 13,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 80,
    occupancyIndex: 1.13,
    waitBaseDays: 38,
    waitVarianceDays: 12,
    sortOrder: 41,
    speiseraum: true,
    besonderheit: "garten",
    room: "zweibett",
    wahl: "unbekannt",
    lage: "Harz, Elbingerode, diakonisches Suchthaus.",
    fokus: "Entwöhnung Alkohol und Medikamente in Höhenlage.",
    facts: [
      "Harzlage, reizarme Umgebung.",
      "Diakonischer Träger.",
      "Illegale Drogen nicht der Kernauftrag.",
    ],
  },
  {
    id: "ck-bramstedt",
    name: "Schön Klinik Bad Bramstedt",
    shortName: "Bad Bramstedt",
    city: "Bad Bramstedt",
    plz: "24576",
    street: "Birkenweg 10",
    stateCode: "SH",
    stateName: "Schleswig-Holstein",
    traeger: "Schön Klinik",
    traegerArt: "privat",
    phone: "04192 504-7600",
    email: NA,
    website: "https://www.schoen-klinik.de/bad-bramstedt",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho, "trauma"],
    therapyForms: [...einzelGruppe, "Verhaltenstherapie"],
    durationWeeksMin: 6,
    durationWeeksMax: 10,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: true,
    jungeErwachsene: false,
    placesEstimate: 280,
    occupancyIndex: 1.2,
    waitBaseDays: 50,
    waitVarianceDays: 14,
    sortOrder: 42,
    speiseraum: true,
    besonderheit: "garten",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Bad Bramstedt zwischen Hamburg und Kiel, großes psychosomatisches Haus.",
    fokus: "Psychosomatik mit Verhaltenstherapie-Schwerpunkt, Traumafokus nach Einschätzung.",
    facts: [
      "Eines der größeren psychosomatischen Häuser im Norden.",
      "Kein Sucht-Entwöhnungsauftrag.",
      "Parkgelände, Kurort.",
    ],
  },
  {
    id: "ck-salza",
    name: "Celenus Klinik an der Salza",
    shortName: "an der Salza",
    city: "Bad Langensalza",
    plz: "99947",
    street: "Kurpromenade",
    stateCode: "TH",
    stateName: "Thüringen",
    traeger: "Celenus Kliniken",
    traegerArt: "privat",
    phone: "0781-932036-0",
    email: "info@celenus-kliniken.de",
    website: "https://www.celenus-kliniken.de",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 4,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 120,
    occupancyIndex: 1.1,
    waitBaseDays: 32,
    waitVarianceDays: 10,
    sortOrder: 43,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett-mehrheit",
    wahl: "unbekannt",
    lage: "Bad Langensalza, Thüringer Kurstadt an der Salza.",
    fokus: "Psychosomatische AHB und Heilverfahren.",
    facts: [
      "Kurpark und Gradierwerk im Ort.",
      "Kein Sucht-Entwöhnungsauftrag.",
      "Celenus-Gruppe.",
    ],
  },
  {
    id: "ck-burgklinik",
    name: "Dr. Becker Burg-Klinik",
    shortName: "Burg-Klinik",
    city: "Stadtlengsfeld",
    plz: "36457",
    street: "Burgstraße",
    stateCode: "TH",
    stateName: "Thüringen",
    traeger: "Dr. Becker Klinikgruppe",
    traegerArt: "privat",
    phone: "036965 68-0",
    email: "info.burg-klinik@dbkg.de",
    website: "https://www.dbkg.de",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 5,
    durationWeeksMax: 7,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 100,
    occupancyIndex: 1.12,
    waitBaseDays: 34,
    waitVarianceDays: 10,
    sortOrder: 44,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Stadtlengsfeld in der Rhön, Dr.-Becker-Gruppe.",
    fokus: "Psychosomatische Rehabilitation in Rhönlage.",
    facts: [
      "Burg- und Hanglage, reizarme Umgebung.",
      "Kein Sucht-Entwöhnungsauftrag.",
      "Kleine Kurort-Infrastruktur.",
    ],
  },
  {
    id: "ck-motzen",
    name: "Fontane-Klinik Motzen",
    shortName: "Fontane Motzen",
    city: "Mittenwalde",
    plz: "15749",
    street: "Am See",
    stateCode: "BB",
    stateName: "Brandenburg",
    traeger: "Träger vor Ort",
    traegerArt: "gemeinnuetzig",
    phone: "033769 86-0",
    email: "info@fontane-klinik.de",
    website: "https://www.fontane-klinik.de",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 5,
    durationWeeksMax: 8,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 90,
    occupancyIndex: 1.11,
    waitBaseDays: 32,
    waitVarianceDays: 10,
    sortOrder: 45,
    speiseraum: true,
    besonderheit: "garten",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Motzen bei Mittenwalde, Seelage südlich von Berlin.",
    fokus: "Psychosomatische Rehabilitation in Seelage.",
    facts: [
      "Motzener See unmittelbar.",
      "Kein Sucht-Entwöhnungsauftrag.",
      "Berlin in Pendelweite für Belastungserprobung.",
    ],
  },
  {
    id: "ck-vitus",
    name: "Fachklinik St. Vitus",
    shortName: "St. Vitus",
    city: "Visbek",
    plz: "49429",
    street: "Vitusstraße",
    stateCode: "NI",
    stateName: "Niedersachsen",
    traeger: "Caritas / Träger vor Ort",
    traegerArt: "kirche",
    phone: "04445 899-0",
    email: "info@sucht-fachkliniken.de",
    website: "https://www.fachklinik-st-vitus.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: false,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...suchtAlkMed],
    therapyForms: [...einzelGruppe, "Seelsorge"],
    durationWeeksMin: 13,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 85,
    occupancyIndex: 1.14,
    waitBaseDays: 40,
    waitVarianceDays: 12,
    sortOrder: 46,
    speiseraum: true,
    besonderheit: "werkstatt",
    room: "zweibett",
    wahl: "unbekannt",
    lage: "Visbek im Oldenburger Münsterland, kirchliches Suchthaus.",
    fokus: "Entwöhnung Alkohol und Medikamente.",
    facts: [
      "Ländliche Lage, wenig städtische Reize.",
      "Illegale Drogen nicht der Kernauftrag.",
      "Seelsorge im Angebot.",
    ],
  },
  {
    id: "ck-osterholz",
    name: "RehaCentrum Alt-Osterholz",
    shortName: "Alt-Osterholz",
    city: "Bremen",
    plz: "28325",
    street: "Osterholzer Landstraße 49a",
    stateCode: "HB",
    stateName: "Bremen",
    traeger: "Therapiehilfe gGmbH",
    traegerArt: "gemeinnuetzig",
    phone: "0421 809490",
    email: "rehacentrum@therapiehilfe.de",
    website: "https://www.therapiehilfe.de/standorte/rehacentrum-alt-osterholz/",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: true,
    substMittel: NA,
    substances: [...suchtAll, "substitution"],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "beides",
    ahb: false,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 80,
    occupancyIndex: 1.19,
    waitBaseDays: 42,
    waitVarianceDays: 12,
    sortOrder: 47,
    speiseraum: true,
    besonderheit: "werkstatt",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Bremen-Osterholz, denkmalgeschütztes Parkgelände nahe Klinikum Bremen-Ost.",
    fokus: "Entwöhnung inkl. Drogen in Bremen; Substitution nach Hausregel.",
    facts: [
      "80 stationäre Plätze plus 20 ganztägig-ambulante Plätze.",
      "Stationär: Einzelzimmer mit eigenem Bad im Neubau. Tagesklinik im Altbau.",
      "Träger Therapiehilfe, federführend DRV Oldenburg-Bremen.",
      "Substitutionsmittel: Angabe liegt nicht vor.",
    ],
  },
  {
    id: "ck-udersleben",
    name: "salus Klinik Udersleben",
    shortName: "Udersleben",
    city: "Kyffhäuserland",
    plz: "99707",
    street: "Udersleben",
    stateCode: "TH",
    stateName: "Thüringen",
    traeger: "salus kliniken",
    traegerArt: "privat",
    phone: NA,
    email: "s.igelmund@salus-kliniken.de",
    website: "https://www.salus-kliniken.de",
    indicationAreas: ["sucht"],
    alkohol: true,
    drogen: true,
    medikamente: true,
    gluecksspiel: false,
    substitution: false,
    substMittel: NA,
    substances: [...suchtAll],
    therapyForms: [...einzelGruppe, "Arbeitstherapie"],
    durationWeeksMin: 12,
    durationWeeksMax: 16,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: false,
    heilverfahren: true,
    barrierefrei: false,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 90,
    occupancyIndex: 1.15,
    waitBaseDays: 40,
    waitVarianceDays: 12,
    sortOrder: 48,
    speiseraum: true,
    besonderheit: "garten",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Kyffhäuser, Thüringen, salus-Suchtklinik in ländlicher Lage.",
    fokus: "Entwöhnung bei stoffgebundenen Abhängigkeiten.",
    facts: [
      "Reizarme Kyffhäuser-Lage.",
      "salus-Gruppe, gemischtes Haus (nicht das Frauenhaus Hürth).",
      "Substitutionsmittel: Angabe liegt nicht vor.",
    ],
  },
  {
    id: "ck-hainberg",
    name: "Klinik am Hainberg",
    shortName: "Hainberg",
    city: "Bad Hersfeld",
    plz: "36251",
    street: "Am Hainberg",
    stateCode: "HE",
    stateName: "Hessen",
    traeger: "Träger vor Ort",
    traegerArt: "gemeinnuetzig",
    phone: "0 6621 173-0",
    email: "info@klinik-am-hainberg.de",
    website: "https://www.klinik-am-hainberg.de",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 5,
    durationWeeksMax: 7,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 110,
    occupancyIndex: 1.11,
    waitBaseDays: 32,
    waitVarianceDays: 10,
    sortOrder: 49,
    speiseraum: true,
    besonderheit: "garten",
    room: "einbett",
    wahl: "unbekannt",
    lage: "Bad Hersfeld, Hanglage am Hainberg.",
    fokus: "Psychosomatische Rehabilitation.",
    facts: [
      "Kurstadt Bad Hersfeld, Festspielstadt.",
      "Kein Sucht-Entwöhnungsauftrag.",
      "Park- und Hanglage.",
    ],
  },
  {
    id: "ck-flechtingen",
    name: "MEDIAN Klinik Flechtingen",
    shortName: "Flechtingen",
    city: "Flechtingen",
    plz: "39345",
    street: "Lindenstraße",
    stateCode: "ST",
    stateName: "Sachsen-Anhalt",
    traeger: "MEDIAN Kliniken",
    traegerArt: "privat",
    phone: "039054 82-0",
    email: "kontakt.flechtingen@median-kliniken.de",
    website: "https://www.median-kliniken.de/de/klinik-flechtingen/",
    indicationAreas: ["psychosomatik"],
    alkohol: null,
    drogen: null,
    medikamente: null,
    gluecksspiel: false,
    substitution: false,
    substMittel: "nicht angeboten",
    substances: [...psycho],
    therapyForms: [...einzelGruppe],
    durationWeeksMin: 4,
    durationWeeksMax: 6,
    genderSetting: "gemischt",
    setting: "stationaer",
    ahb: true,
    heilverfahren: true,
    barrierefrei: true,
    angehoerigenarbeit: true,
    kinderbetreuung: false,
    trauma: false,
    jungeErwachsene: false,
    placesEstimate: 150,
    occupancyIndex: 1.1,
    waitBaseDays: 30,
    waitVarianceDays: 9,
    sortOrder: 50,
    speiseraum: true,
    besonderheit: "garten",
    room: "unbekannt",
    wahl: "unbekannt",
    lage: "Flechtingen in der Magdeburger Börde, Schloss- und Parklage.",
    fokus: "Psychosomatische Rehabilitation inkl. AHB.",
    facts: [
      "Schlosspark Flechtingen unmittelbar.",
      "Kein Sucht-Entwöhnungsauftrag.",
      "MEDIAN-Haus in ländlicher Börde.",
    ],
  },
];

export const HOUSES: HouseSpec[] = [...HOUSES_CORE, ...HOUSES_EXTRA];
