/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KlarOMatRouteImport } from './routes/klar-o-mat'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as UeberRouteImport } from './routes/ueber'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppKlarOMatRouteImport } from './routes/app/klar-o-mat'
import { Route as AppProfilRouteImport } from './routes/app/profil'
import { Route as EinladungTokenRouteImport } from './routes/einladung.$token'
import { Route as KlinikenIndexRouteImport } from './routes/kliniken/index'
import { Route as KlinikenClinicIdRouteImport } from './routes/kliniken/$clinicId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppFallordnerIndexRouteImport } from './routes/app/fallordner/index'
import { Route as AppFallordnerFolderIdRouteImport } from './routes/app/fallordner/$folderId'
import { Route as AppTeamIndexRouteImport } from './routes/app/team/index'
import { Route as AppTeamTeamIdRouteImport } from './routes/app/team/$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KlarOMatRoute = KlarOMatRouteImport.update({
  id: '/klar-o-mat',
  path: '/klar-o-mat',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberRoute = UeberRouteImport.update({
  id: '/ueber',
  path: '/ueber',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppKlarOMatRoute = AppKlarOMatRouteImport.update({
  id: '/klar-o-mat',
  path: '/klar-o-mat',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const EinladungTokenRoute = EinladungTokenRouteImport.update({
  id: '/einladung/$token',
  path: '/einladung/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const KlinikenIndexRoute = KlinikenIndexRouteImport.update({
  id: '/kliniken/',
  path: '/kliniken/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlinikenClinicIdRoute = KlinikenClinicIdRouteImport.update({
  id: '/kliniken/$clinicId',
  path: '/kliniken/$clinicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFallordnerIndexRoute = AppFallordnerIndexRouteImport.update({
  id: '/fallordner/',
  path: '/fallordner/',
  getParentRoute: () => AppRoute,
} as any)
const AppFallordnerFolderIdRoute = AppFallordnerFolderIdRouteImport.update({
  id: '/fallordner/$folderId',
  path: '/fallordner/$folderId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamTeamIdRoute = AppTeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/klar-o-mat': typeof KlarOMatRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/ueber': typeof UeberRoute
  '/app/klar-o-mat': typeof AppKlarOMatRoute
  '/app/profil': typeof AppProfilRoute
  '/einladung/$token': typeof EinladungTokenRoute
  '/kliniken/$clinicId': typeof KlinikenClinicIdRoute
  '/app/': typeof AppIndexRoute
  '/kliniken/': typeof KlinikenIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/fallordner/$folderId': typeof AppFallordnerFolderIdRoute
  '/app/team/$teamId': typeof AppTeamTeamIdRoute
  '/app/fallordner/': typeof AppFallordnerIndexRoute
  '/app/team/': typeof AppTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/klar-o-mat': typeof KlarOMatRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/ueber': typeof UeberRoute
  '/app/klar-o-mat': typeof AppKlarOMatRoute
  '/app/profil': typeof AppProfilRoute
  '/einladung/$token': typeof EinladungTokenRoute
  '/kliniken/$clinicId': typeof KlinikenClinicIdRoute
  '/app': typeof AppIndexRoute
  '/kliniken': typeof KlinikenIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/fallordner/$folderId': typeof AppFallordnerFolderIdRoute
  '/app/team/$teamId': typeof AppTeamTeamIdRoute
  '/app/fallordner': typeof AppFallordnerIndexRoute
  '/app/team': typeof AppTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/klar-o-mat': typeof KlarOMatRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/ueber': typeof UeberRoute
  '/app/klar-o-mat': typeof AppKlarOMatRoute
  '/app/profil': typeof AppProfilRoute
  '/einladung/$token': typeof EinladungTokenRoute
  '/kliniken/$clinicId': typeof KlinikenClinicIdRoute
  '/app/': typeof AppIndexRoute
  '/kliniken/': typeof KlinikenIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/fallordner/$folderId': typeof AppFallordnerFolderIdRoute
  '/app/team/$teamId': typeof AppTeamTeamIdRoute
  '/app/fallordner/': typeof AppFallordnerIndexRoute
  '/app/team/': typeof AppTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/datenschutz'
    | '/impressum'
    | '/klar-o-mat'
    | '/login'
    | '/logout'
    | '/ueber'
    | '/app/klar-o-mat'
    | '/app/profil'
    | '/einladung/$token'
    | '/kliniken/$clinicId'
    | '/app/'
    | '/kliniken/'
    | '/api/auth/$'
    | '/app/fallordner/$folderId'
    | '/app/team/$teamId'
    | '/app/fallordner/'
    | '/app/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/klar-o-mat'
    | '/login'
    | '/logout'
    | '/ueber'
    | '/app/klar-o-mat'
    | '/app/profil'
    | '/einladung/$token'
    | '/kliniken/$clinicId'
    | '/app'
    | '/kliniken'
    | '/api/auth/$'
    | '/app/fallordner/$folderId'
    | '/app/team/$teamId'
    | '/app/fallordner'
    | '/app/team'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/datenschutz'
    | '/impressum'
    | '/klar-o-mat'
    | '/login'
    | '/logout'
    | '/ueber'
    | '/app/klar-o-mat'
    | '/app/profil'
    | '/einladung/$token'
    | '/kliniken/$clinicId'
    | '/app/'
    | '/kliniken/'
    | '/api/auth/$'
    | '/app/fallordner/$folderId'
    | '/app/team/$teamId'
    | '/app/fallordner/'
    | '/app/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KlarOMatRoute: typeof KlarOMatRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  UeberRoute: typeof UeberRoute
  EinladungTokenRoute: typeof EinladungTokenRoute
  KlinikenClinicIdRoute: typeof KlinikenClinicIdRoute
  KlinikenIndexRoute: typeof KlinikenIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klar-o-mat': {
      id: '/klar-o-mat'
      path: '/klar-o-mat'
      fullPath: '/klar-o-mat'
      preLoaderRoute: typeof KlarOMatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber': {
      id: '/ueber'
      path: '/ueber'
      fullPath: '/ueber'
      preLoaderRoute: typeof UeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/klar-o-mat': {
      id: '/app/klar-o-mat'
      path: '/klar-o-mat'
      fullPath: '/app/klar-o-mat'
      preLoaderRoute: typeof AppKlarOMatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profil': {
      id: '/app/profil'
      path: '/profil'
      fullPath: '/app/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/einladung/$token': {
      id: '/einladung/$token'
      path: '/einladung/$token'
      fullPath: '/einladung/$token'
      preLoaderRoute: typeof EinladungTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kliniken/': {
      id: '/kliniken/'
      path: '/kliniken'
      fullPath: '/kliniken/'
      preLoaderRoute: typeof KlinikenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kliniken/$clinicId': {
      id: '/kliniken/$clinicId'
      path: '/kliniken/$clinicId'
      fullPath: '/kliniken/$clinicId'
      preLoaderRoute: typeof KlinikenClinicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/fallordner/': {
      id: '/app/fallordner/'
      path: '/fallordner'
      fullPath: '/app/fallordner/'
      preLoaderRoute: typeof AppFallordnerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fallordner/$folderId': {
      id: '/app/fallordner/$folderId'
      path: '/fallordner/$folderId'
      fullPath: '/app/fallordner/$folderId'
      preLoaderRoute: typeof AppFallordnerFolderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team/': {
      id: '/app/team/'
      path: '/team'
      fullPath: '/app/team/'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team/$teamId': {
      id: '/app/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/app/team/$teamId'
      preLoaderRoute: typeof AppTeamTeamIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppKlarOMatRoute: typeof AppKlarOMatRoute
  AppProfilRoute: typeof AppProfilRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFallordnerFolderIdRoute: typeof AppFallordnerFolderIdRoute
  AppTeamTeamIdRoute: typeof AppTeamTeamIdRoute
  AppFallordnerIndexRoute: typeof AppFallordnerIndexRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppKlarOMatRoute: AppKlarOMatRoute,
  AppProfilRoute: AppProfilRoute,
  AppIndexRoute: AppIndexRoute,
  AppFallordnerFolderIdRoute: AppFallordnerFolderIdRoute,
  AppTeamTeamIdRoute: AppTeamTeamIdRoute,
  AppFallordnerIndexRoute: AppFallordnerIndexRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KlarOMatRoute: KlarOMatRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  UeberRoute: UeberRoute,
  EinladungTokenRoute: EinladungTokenRoute,
  KlinikenClinicIdRoute: KlinikenClinicIdRoute,
  KlinikenIndexRoute: KlinikenIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
